#----------------------------------------------------------------------------------------------------------------------
# The following are the general values used to deploy an AnyLog instance of type: REST | AnyLog version: develop
#----------------------------------------------------------------------------------------------------------------------
general:
  namespace: default
  hostname: anylog-node
  app_name: anylog
  pod_name: anylog-pod
  deployment_name: anylog-app
  service_name: anylog-svs
  configmap_name: anylog-configs
  # nodeSelector - Allows running Kubernetes remotely. If commented out, code will ignore it
  nodeSelector: ""
  replicas: 1

  
image:
  secretName: imagepullsecret
  repository: anylogco/anylog-network
  tag: develop
  pullPolicy: IfNotPresent

volume:
  enable_volume: true
  anylog_volume_name: anylog-node-anylog
  blockchain_volume_name: anylog-node-blockchain
  data_volume_name: anylog-node-data
  # claim for when using Remote-CLI for image data
  # remote_cli: remote-cli-blobs-volume

configs:
  basic:
    node_type: rest
    node_name: anylog-node
    company_name: new company
    # if location is not set, will use `https://ipinfo.io/json` to get coordinates
    location: ""

  networking:
    server: 32048
    rest: 32049
    # Optional broker port
    broker: ""
    external_ip: ""
    local_ip: ""
    # Proxy IP used by Nginx or other loadbalancer
    k8s_proxy_ip: ""

  authentication:
    enable: false
    type: ""
    user: ""
    password: ""

  settings:
    # whether to deploy a local script that extends the default startup script
    deploy_local_script: "false"
    # An optional parameter for the number of workers threads that process requests which are send to the provided IP and Port.
    tcp_thread_pool: 6
    # Amount of time (in seconds) until REST timeout
    rest_timeout: 30
    # The number of concurrent threads supporting HTTP requests.
    rest_threads: 5
    # Sets the number of threads supporting queries (the default is 3).
    query_pool: 3
    write_immediate: true
    threshold_time : 60 seconds
    threshold_volume: 10kb



