configs:
  general:
    name: node-configurations
  ports:
    anylog_server_port: 32048
    anylog_rest_port: 32049
    anylog_broker_port: 3250

deployments:
  general:
    app: anylog-node
    name: anylog-node
  image:
    imagePullSecrets: imagepullsecret
    image: anylogco/anylog-network:predevelop
    pullPolicy: Always




