#----------------------------------------------------------------------------------------------------------------------
# The following are the general values used to deploy an AnyLog instance of type: REST | AnyLog version: develop
#----------------------------------------------------------------------------------------------------------------------
general:
  #namespace: anylog-network
  name: anylog
  replicas: 1

image:
  set_secret: true
  secretName: imagepullsecret
  name: anylogco/anylog-network
  version: develop
  pullPolicy: IfNotPresent

configs:
  basic:
    node_type: "rest"
    node_name: "anylog-node"
    company: "new company"
  networking:
    services:
      anylog_server_port: 32048
      anylog_rest_port: 32049
      # OPTIONAL - MQTT message broker on AnyLog node
      anylog_broker_port: 32050
    network_ips:
      external_ip: ""
      local_ip: ""
    settings:
      # OPTIONAL - whether to enable local MQTT message broker or not
      enable_broker: "true"
      # TCP connection information for master node (not needed for REST node)
      master_node: ""
      # How often a node syncs with the master node
      sync_time: ""

