deployments:
  general:
    app: anylog-node
    name: anylog-node
  image:
    imagePullSecrets: imagepullsecret
    image: anylogco/anylog-network:predevelop
    pullPolicy: Always

configs:
  basic:
    node_type: "rest"
    node_name: "anylog-node"
    company: "new company"

  networking:
    services:
      service_type: NodePort
      anylog_server_port: 32048
      anylog_rest_port: 32049
      anylog_broker_port: 32050
    network_ips:
      external_ip: "127.0.0.1"
      local_ip: "127.0.0.1"
    settings:
      master_node: "127.0.0.1:2048"
      enable_broker: "true"
      change_external_ip: "false"
      change_local_ip: "false"
