#----------------------------------------------------------------------------------------------------------------------
# The following are the general values used to deploy an AnyLog instance of type: REST | AnyLog version: develop
#----------------------------------------------------------------------------------------------------------------------
general:
  namespace: anylog-network
  name: anylog
  replicas: 1

image:
  set_secret: true
  secretName: imagepullsecret
  name: anylogco/anylog-network
  version: develop
  pullPolicy: IfNotPresent

configs:
  basic:
    node_type: "rest"
    node_name: "anylog-node"
    company: "new company"
  networking:
    services:
      anylog_server_port: 32048
      anylog_rest_port: 32049
      # OPTIONAL - MQTT message broker on AnyLog node
      anylog_broker_port: 32050
    network_ips:
      external_ip: ""
      local_ip: ""
    settings:
      # whether to deploy a local script that extends the default startup script
      deploy_local_script: "false"
      # An optional parameter for the number of workers threads that process requests which are send to the provided IP and Port.
      tcp_thread_pool: 6
      # Amount of time (in seconds) until REST timeout
      rest_timeout: 30
      # The number of concurrent threads supporting HTTP requests.
      rest_threads: 5
      # Sets the number of threads supporting queries (the default is 3).
      query_pool: 3


