apiVersion: v1
kind: ConfigMap
metadata:
  namespace: '{{ .Values.metadata.namespace }}'
  name: '{{ .Values.metadata.configmap_name }}'
  labels:
    app: '{{ .Values.metadata.app_name }}'
data:
  # -- Directories --
  ANYLOG_PATH: '{{ .Values.node_configs.directories.ANYLOG_PATH }}'
  LOCAL_SCRIPTS: '{{ .Values.node_configs.directories.LOCAL_SCRIPTS }}'
  TEST_DIR: '{{ .Values.node_configs.directories.TEST_DIR }}'

  # -- General --
  LICENSE_KEY: '{{ .Values.node_configs.general.LICENSE_KEY }}'
  NODE_TYPE: '{{ .Values.node_configs.general.NODE_TYPE }}'
  NODE_NAME: '{{ .Values.node_configs.general.NODE_NAME }}'
  COMPANY_NAME: '{{ .Values.node_configs.general.COMPANY_NAME }}'

  # -- Geolocation --
  {{ if ne .Values.node_configs.geolocation.LOCATION "" }}
  LOCATION: '{{ .Values.node_configs.geolocation.LOCATION }}'
  {{ end }}
  {{ if ne .Values.node_configs.geolocation.COUNTRY "" }}
  COUNTRY: '{{ .Values.node_configs.geolocation.COUNTRY }}'
  {{ end }}
  {{ if ne .Values.node_configs.geolocation.STATE "" }}
  STATE: '{{ .Values.node_configs.geolocation.STATE }}'
  {{ end }}
  {{ if ne .Values.node_configs.geolocation.CITY "" }}
  CITY: '{{ .Values.node_configs.geolocation.CITY }}'
  {{ end }}

  # -- Networking --
  ANYLOG_SERVER_PORT: {{ .Values.node_configs.networking.ANYLOG_SERVER_PORT }}
  ANYLOG_REST_PORT: {{ .Values.node_configs.networking.ANYLOG_REST_PORT }}

  {{ if new .Values.node_configs.networking.CONFIG_NAME "" }}
  CONFIG_NAME: '{{ .Values.node_configs.networking.CONFIG_NAME }}'
  {{ end }}

  {{ if new .Values.node_configs.networking.OVERLAY_IP "" }}
  OVERLAY_IP: '{{ .Values.node_configs.networking.OVERLAY_IP }}'
  {{ end }}

  {{ if new .Values.node_configs.networking.PROXY_IP "" }}
  PROXY_IP: '{{ .Values.node_configs.networking.PROXY_IP }}'
  {{ end }}

  {{ if new .Values.node_configs.networking.ANYLOG_BROKER_PORT "" }}
  ANYLOG_BROKER_PORT: {{ .Values.node_configs.networking.ANYLOG_BROKER_PORT }}
  {{ end }}





