#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name:
#  labels:
#    app:
#data:
#  NODE_TYPE: {{ .Values.configs.basic.node_type }}
#  NODE_NAME: {{ .Values.configs.basic.node_name }}
#  COMPANY_NAME: {{ .Values.configs.basic.company }}
#
#  #EXTERNAL_IP: <EXTERNAL IP>
#  #LOCAL_IP: <LOCAL IP>
#  ANYLOG_SERVER_PORT: "32048"
#  ANYLOG_REST_PORT: "32049"
#  ANYLOG_BROKER_PORT: 32050"
#
##  ANYLOG_SERVER_PORT: {{ .Values.configs.networking.anylog_server_port }}
##  ANYLOG_REST_PORT: {{ .Values.configs.networking.anylog_rest_port }}
##  ANYLOG_BROKER_PORT: {{ .Values.configs.networking.anylog_broker_port }}
#  ENABLE_BROKER: {{ .Values.configs.networking.enable_broker }}
#

apiVersion: v1
kind: ConfigMap
  metadata:
    name: {{ .Values.deployments.general.name }}-configmap
  labels:
    app: {{ .Values.deployments.general.app }}
  data:
    NODE_TYPE: {{ .Values.configs.basic.node_type }}
    NODE_NAME: {{ .Values.configs.basic.node_name }}
    COMPANY_NAME: {{ .Values.configs.basic.company }}

    #EXTERNAL_IP: <EXTERNAL IP>
    #LOCAL_IP: <LOCAL IP>
    ANYLOG_SERVER_PORT: {{ .Values.configs.networking.anylog_server_port }}
    ANYLOG_REST_PORT: {{ .Values.configs.networking.anylog_rest_port }}
    MASTER_NODE: "127.0.0.1:32048"
    SYNC_TIME: "30 second"

