apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.general.name }}-configurations
  labels:
    app: {{ .Values.general.name }}
data:
  NODE_TYPE: {{ default .Values.configs.basic.node_type "rest" }}
  NODE_NAME: {{ default .Values.configs.basic.node_name "anylog-node" }}
  COMPANY_NAME: {{ default .Values.configs.basic.company  "new company" }}

  {{ if .Values.configs.networking.network_ips.external_ip  }}
  EXTERNAL_IP: {{ .Values.configs.networking.network_ips.external_ip }}
  {{ end }}

  {{ if .Values.configs.networking.network_ips.local_ip  }}
  LOCAL_IP: {{ .Values.configs.networking.network_ips.local_ip }}
  {{ end }}

  ANYLOG_SERVER_PORT: {{ default .Values.configs.networking.services.anylog_server_port "32048" | quote }}
  ANYLOG_REST_PORT: {{ default .Values.configs.networking.services.anylog_rest_port "32049" | quote }}

  ENABLE_BROKER: {{ default .Values.configs.networking.settings.enable_broker "false" | quote }}
  {{ if .Values.configs.networking.settings.enable_broker }}
  ANYLOG_BROKER_PORT: {{ default .Values.configs.networking.services.anylog_rest_port "32050" | quote }}
  {{ end }}
