apiVersion: v1
kind: ConfigMap
metadata:
  namespace: '{{ .Values.metadata.namespace }}'
  name: '{{ .Values.metadata.configmap_name }}'
  labels:
    app: '{{ .Values.metadata.deployment_name }}'
data:
  # -- General Configurations --
  NODE_TYPE: '{{ .Values.general.NODE_TYPE }}'
  NODE_NAME: '{{ .Values.general.NODE_NAME }}'
  COMPANY_NAME: '{{ .Values.general.COMPANY_NAME }}'
  {{ if ne .Values.general.LOCATION "" }}
    LOCATION: '{{ .Values.general.LOCATION }}'
  {{ end }}
