apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.general.name }}configmap
  labels:
    app: {{ .Values.general.name }}
data:
  # General information
  NODE_TYPE: {{ default .Values.configs.basic.node_type "rest"}}
  NODE_NAME: {{ default .Values.configs.basic.node_name "anylog-node" }}
  COMPANY_NAME: {{ default  .Values.configs.basic.node_name "new company" }}
  {{ if .Values.configs.basic.location }} and {{- if ne .Values.configs.basic.location "" }}
    LOCATION: {{ .Values.configs.basic.location }}
  {{ end }} {{ end }}

  # networking
  ANYLOG_SERVER_PORT: {{ .Values.configs.networking.services.anylog_server_port | quote }}
  ANYLOG_REST_PORT: {{ .Values.config.networking.services.anylog_rest_port | quote }}

  {{ if .Values.configs.networking.services.anylog_broker_port }}
    ANYLOG_BROKER_PORT: {{ .Values.configs.networking.services.anylog_broker_port }}
  {{ end }}

  {{- if ne .Values.conifgs.basic.node_type "rest" }}
    MASTER_NODE: {{ .Values.configs.networking.settings.master_node }}
  {{ end }}



