apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployments.general.name }}
  labels:
    app: {{ .Values.deployments.general.app }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.deployments.general.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployments.general.app }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.deployments.image.imagePullSecrets }}
      containers:
      - name: {{ .Values.deployments.general.name }}
        image: {{ .Values.deployments.image.image }}
        imagePullPolicy: {{ .Values.deployments.image.pullPolicy }}
        envFrom:
          - configMapRef:
              name: {{ .Values.configs.general.name }}
        ports:
          - containerPort: {{ .Values.configs.ports.anylog_server_port }}
            name: {{ .Values.deployments.general.name }}-tcp
          - containerPort: { { .Values.configs.ports.anylog_rest_port } }
            name: { { .Values.deployments.general.name } }-rest
          - containerPort: { { .Values.configs.ports.anylog_broker_port } }
            name: { { .Values.deployments.general.name } }-rest