apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.general.name }}
  labels:
    app: {{ .Values.general.name }}
spec:
  replicas: {{ .Values.general.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.general.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.general.name }}
    spec:
      {{ if .Values.image.set_secret }}
      imagePullSecrets:
      - name: {{ .Values.image.secretName }}
      {{ end }}
      containers:
      - name: {{ .Values.general.name }}
        image: {{ .Values.image.name }}:{{ .Values.image.version }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
          - configMapRef:
              name: {{ .Values.general.name }}-configurations
        ports:
          - containerPort: {{ .Values.configs.networking.services.anylog_server_port }}
          - containerPort: {{ .Values.configs.networking.services.anylog_rest_port }}
          {{ if .Values.configs.networking.settings.enable_broker }}
          - containerPort: {{ .Values.configs.networking.services.anylog_rest_port }}
          {{ end }}

