apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.general.name }}-deployment
  labels:
    app: {{ .Values.general.name }}
spec:
  replicas: {{ .Values.general.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.general.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.general.name }}
    spec:
      {{- if ne .Values.image.secretName "" }}
      imagePullSecrets:
        - name: {{ .Values.image.secretName }}
      {{ end }}
      containers:
      - name: {{ .Values.general.basic.node_name }}
        image: {{ .Values.image.name }}:{{ .Values.image.version }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: {{ .Values.general.name }}-configuration
        ports:
        - containerPort: {{ .Values.configs.networking.services.anylog_server_port }}
          name: tcp
        - containerPort: {{ .Values.configs.networking.services.anylog_rest_port }}
          name: rest
        {{ if .Values.configs.networking.services.anylog_broker_port }}
        - containerPort: {{ .Values.configs.networking.services.anylog_rest_port }}
          name: broker
        {{ end }}

