version: "2.2"
services:
  grafana:
    image: grafana/grafana:latest
    env_file:
      - grafana.env
    container_name: grafana
    restart: always
    stdin_open: true
    tty: true
    ports:
      - "3100:3100"
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-log:/var/log/grafana
      - grafana-config:/etc/grafana
volumes:
  grafana-data:
  grafana-log:
  grafana-config:
