metadata: 
  # Kubernetes Instance namespace
  namespace: default
  # hostname for deployment
  hostname: anylog-query
  # deployment application name
  app_name: anylog-query-deployment
  # Pod application name
  pod_name: anylog-query-pod
  # Kubernetes deployment name
  deployment_name: anylog-node-deployment
  # Kubernetes service name
  service_name: anylog-query-svs
  # Kubernetes configuration mapping name
  configmap_name: anylog-query-configs
  # Allows running Kubernetes remotely. If commented out, code will ignore it
  node_selector: 
  # Number of Kubernetes replicas
  replicas: 1

image: 
  # Image secret naming
  secret_name: imagepullsecret
  # (Docker Hub) Image Path
  repository: anylogco/anylog-network
  # Image version
  tag: predevelop
  # Image pulling policy
  pull_policy: IfNotPresent

volume: 
  # Whether or not to enable volumes for AnyLog
  enable_volume: true
  anylog_volume:
    # AnyLog Volume name
    name: anylog-query-anylog-volume
    # AnyLog security directory path
    path: /app/AnyLog-Network/anylog
    # Volume access mode
    access_mode: ReadWRiteOnce
    # Volume storage size
    storage_size: 1Gi
  blockchain_volume:
    # AnyLog Volume name
    name: anylog-query-blockchain-volume
    # AnyLog security directory path
    path: /app/AnyLog-Network/blockchain
    # Volume access mode
    access_mode: ReadWRiteOnce
    # Volume storage size
    storage_size: 1Gi
  data_volume:
    # AnyLog Volume name
    name: anylog-query-data-volume
    # AnyLog security directory path
    path: /app/AnyLog-Network/data
    # Volume access mode
    access_mode: ReadWRiteOnce
    # Volume storage size
    storage_size: 1Gi

