version: "3.4"
services:
  database:
    image: postgres:14.0-alpine
    container_name: postgres
    stdin_open: true
    tty: true
    ports:
      - protocol: tcp
        target: 5432
    networks:
      - frontend
    environment:
      - POSTGRES_USER=anylog
      - POSTGRES_PASSWORD=demo
#    volumes:
#      - /usr/local/postgres:/var/lib/postgresql/:rw
  grafana:
    image: grafana/grafana:7.5.7
    container_name: grafana
    ports:
      - protocol: TCP
        target: 3000
    networks:
      - frontend
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_ALLOW_EMBEDDING=true
      - GF_INSTALL_PLUGINS=simpod-json-datasource,grafana-worldmap-panel
#    volumes:
#      - /usr/local/grafana:/var/lib/grafana:rw
  remote-cli:
    image: anylogco/remote-cli:latest
    container_name: remote-cli
    ports:
      - protocol: TCP
        target: 8000
    networks:
      - frontend
    environment:
      - CONN_IP=127.0.0.1 # IP address should be updated to be your physical IP
      - CONN_PORT=8000
#    volumes:
#      - /app/Remote-CLI/anylog_query/static/json/
  anylog-gui:
    image: anylogco/anylog-gui:latest
    container_name: anylog-gui
    ports:
      - protocol: TCP
        target: 5000
    networks:
      frontend:
    environment:
      - CONFIG_FOLDER=views
      - CONFIG_FILE=testnet.json
#    volumes:
#      - anylog-gui-volume:/app/AnyLog-GUI/
  anylog-node:
    image: anylogco/anylog-network:test
    container_name: anylog-node
    ports:
      - protocol: TCP
        target: 19180
      - protocol: TCP
        target: 19181
      - protocol: TCP
        target: 19182
    networks:
      frontend:
    environment:
      - NODE_TYPE=rest
      - ANYLOG_SERVER_PORT=19180
      - ANYLOG_REST_PORT=19181
      - ANYLOG_BROKER_PORT=19182
networks:
  frontend:
    driver: bridge
    external: true
volumes:
  pgdata:
    external: false
  grafana-data:
    external: false
  remote-cli:
    external: false

#    external: false
#  anylog-gui-volume:
#    external: false

