version: "3.4"
services:
  database:
    image: postgres:14.0-alpine
    env_file:
      - envs/postgres.env
    container_name: postgres
    stdin_open: true
    tty: true
    networks:
      - frontend
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  grafana:
    image: grafana/grafana:7.5.7
    env_file:
      - envs/grafana.env
    container_name: grafana
    stdin_open: true
    tty: true
    networks:
      - frontend
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-log:/var/log/grafana
      - grafana-config:/etc/grafana
  remote-cli:
    image: anylogco/remote-cli:latest
    env_file:
      - envs/anylog_tools.env
    container_name: remote-cli
    stdin_open: true
    tty: true
    networks:
      - frontend
    ports:
      - ${CLI_PORT}:${CLI_PORT}
    volumes:
      - remote-cli:/app/Remote-CLI/anylog_query/static/json
  anylog-gui:
    image: anylogco/anylog-gui:latest
    container_name: anylog-gui
    env_file:
      - envs/anylog_tools.env
    stdin_open: true
    tty: true
    ports:
      - {GUI_PORT}:${GUI_PORT}
    volumes:
      - anylog-gui:/app/AnyLog-GUI/views
  anylog-node:
    image: anylogco/anylog-network:test
    env_file:
      - envs/anylog_node.env
    container_name: anylog-node
    stdin_open: true
    tty: true
    network_mode: host
    ports:
      - ${ANYLOG_SERVR_PORT}:${ANYLOG_SERVR_PORT}
      - ${ANYLOG_REST_PORT}:${ANYLOG_REST_PORT}
      - ${ANYLOG_BROKER_PORT}:${ANYLOG_BROKR_PORT}
    volumes:
      - anylog-node-anylog:/app/AnyLog-Network/anylog
      - anylog-node-blockchain:/app/AnyLog-Network/blockchain
      - anylog-node-data:/app/AnyLog-Network/data
      - anylog-node-local-scripts:/app/AnyLog-Network/local_scripts
networks:
  frontend:
    driver: bridge
    external: false
volumes:
  pgdata:
  grafana-data:
  grafana-log:
  grafana-config:
  remote-cli:
  anylog-gui:
  anylog-node-anylog:
  anylog-node-blockchain:
  anylog-node-data:
  anylog-node-local-scripts:
