networks:
  frontend:
    driver: bridge
    external: false
services:
  anylog-gui:
    container_name: anylog-gui
    environment:
      CONFIG_FILE: testnet.json
      CONFIG_FOLDER: views
      CONN_IP: 127.0.0.1
      GUI_PORT: '5000'
    image: anylogco/anylog-gui:latest
    networks:
      frontend: null
    ports:
    - published: 5000
      target: 5000
    stdin_open: true
    tty: true
    volumes:
    - anylog-gui:/app/AnyLog-GUI/views:rw
  anylog-node:
    container_name: anylog-node
    environment:
      ANYLOG_BROKER_PORT: '3482'
      ANYLOG_REST_PORT: '3481'
      ANYLOG_SERVER_PORT: '3480'
      BROKER: driver.cloudmqtt.com
      CLUTSER_NAME: new-cluster
      COMPANY_NAME: AnyLog
      DATA_MONITOR_COLUMN: value
      DATA_MONITOR_INTERVAL: '"1 minute"'
      DB_PORT: '5432'
      DB_TYPE: psql
      DB_USER: '[POSTGRES_USER]@[IP_ADDRESS]:[POSTGRES_PASSWORD]'
      DEFAULT_DBMS: test
      ENABLE_DATA_MONITOR: "false"
      ENABLE_PARTITION: "true"
      INTERVAL_VALUE: '10'
      MASTER_NODE: 45.33.41.185:2048
      MQTT_COLUMN_TIMESTAMP: now
      MQTT_COLUMN_VALUE: '"bring [readings][][value]"'
      MQTT_COLUMN_VALUE_TYPE: float
      MQTT_ENABLE: "true"
      MQTT_LOG: "false"
      MQTT_PASSWORD: MSY4e009J7ts
      MQTT_PORT: '18785'
      MQTT_TOPIC_DBMS: test
      MQTT_TOPIC_NAME: anylogedgex
      MQTT_TOPIC_TABLE: '"bring [device]"'
      MQTT_USER: ibglowct
      NODE_NAME: anylog-node
      NODE_TYPE: rest
      PARTITION_COLUMN: timestamp
      PARTITION_INTERVAL: '"7 days"'
      PARTITION_KEEP: '42'
      SYNC_TIME: '"30 second"'
      TABLE_NAME: '*'
    image: anylogco/anylog-network:test
    networks:
      frontend: null
    ports:
    - published: 13480
      target: 13480
    - published: 13481
      target: 13481
    - published: 13482
      target: 13482
    stdin_open: true
    tty: true
    volumes:
    - anylog-node-anylog:/app/AnyLog-Network/anylog:rw
    - anylog-node-blockchain:/app/AnyLog-Network/blockchain:rw
    - anylog-node-data:/app/AnyLog-Network/data:rw
    - anylog-node-local-scripts:/app/AnyLog-Network/local-scripts:rw
  database:
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: passwd
      POSTGRES_USER: admin
    image: postgres:14.0-alpine
    networks:
      frontend: null
    ports:
    - published: 5432
      target: 5432
    stdin_open: true
    tty: true
    volumes:
    - pgdata:/var/lib/postgresql:rw
  grafana:
    container_name: grafana
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_DISABLE_LOGIN_FORM: "false"
      GF_INSTALL_PLUGINS: simpod-json-datasource,grafana-worldmap-panel
      GF_SECURITY_ALLOW_EMBEDDING: "true"
      GRAFANA_ADMIN_PASSWORD: passwd
      GRAFANA_ADMIN_USER: admin
    image: grafana/grafana:7.5.7
    networks:
      frontend: null
    ports:
    - published: 3000
      target: 3000
    stdin_open: true
    tty: true
    volumes:
    - grafana-data:/var/lib/grafana:rw
  remote-cli:
    container_name: remote-cli
    environment:
      CLI_PORT: '8000'
      CONN_IP: 127.0.0.1
    image: anylogco/remote-cli:latest
    networks:
      frontend: null
    ports:
    - published: 8000
      target: 8000
    stdin_open: true
    tty: true
    volumes:
    - remote-cli:/app/Remote-CLI/anylog_query/static/json:rw
version: '3.4'
volumes:
  anylog-gui:
    external: false
  anylog-node-anylog:
    external: false
  anylog-node-blockchain:
    external: false
  anylog-node-data:
    external: false
  anylog-node-local-scripts:
    external: false
  grafana-data:
    external: false
  pgdata:
    external: false
  remote-cli:
    external: false

