version: "3.4"
services:
  database:
    image: postgres:14.0-alpine
    env_file:
      - envs/postgres.env
    container_name: postgres
    stdin_open: true
    tty: true
    networks:
      - frontend
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  grafana:
    image: grafana/grafana:7.5.7
    env_file:
      - envs/grafana.env
    container_name: grafana
    stdin_open: true
    tty: true
    networks:
      - frontend
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
  remote-cli:
    image: anylogco/remote-cli:latest
    env_file:
      - envs/remote_cli.env
    container_name: remote-cli
    stdin_open: true
    tty: true
    networks:
      - frontend
    ports:
      - "8000:8000"
    volumes:
      - remote-cli:/app/Remote-CLI
  anylog-gui:
    image: anylogco/anylog-gui:latest
    container_name: anylog-gui
    env_file:
      - envs/anylog_gui.env
    stdin_open: true
    tty: true
    networks:
      - frontend
    ports:
      - "5000:5000"
  anylog-node:
    image: anylogco/anylog-network:test
    env_file:
      - envs/anylog_node.env
    container_name: anylog-node
    stdin_open: true
    tty: true
    networks:
      - frontend
    ports:
      - "13480:13480"
      - "13481:13481"
      - "13482:13482"
networks:
  frontend:
    driver: bridge
    external: false
volumes:
  pgdata:
  grafana-data:
  remote-cli:

