version: "3.4"
services:
  database:
    image: postgres:14.0-alpine
    container_name: postgres
    stdin_open: true
    tty: true
    ports:
      - 5432:5432
    networks:
      - frontend
    environment:
      - POSTGRES_USER=anylog
      - POSTGRES_PASSWORD=demo
    volumes:
      - pgdata:/var/lib/postgresql/
  grafana:
    image: grafana/grafana:7.5.7
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - frontend
    environment:
      - GF_INSTALL_PLUGINS=simpod-json-datasource,grafana-worldmap-panel
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-log:/var/log/grafana
      - grafana-config:/etc/grafana
  anylog-node:
    image: anylogco/anylog-network:test
    container_name: anylog-node
    ports:
      - "3481:3841"
    networks:
      - frontend
    environment:
      - NODE_TYPE=rest
      - ANYLOG_REST_PORT=3481
networks:
  frontend:
volumes:
  pgdata:
    external: false
  grafana-data:
    external: false
  grafana-log:
    external: false
  grafana-config:
    external: false


