metadata:
  # Kubernetes Instance namespace
  namespace: default
  # hostname for deployment
  hostname: anylog-master
  # deployment application name
  app_name: anylog-master-app
  # Pod application name
  pod_name: anylog-master-pod
  # Kubernetes deployment name
  deployment_name: anylog-master-deployment
  # Kubernetes service name
  service_name: anylog-master-service
  # Configuration file mapping name
  configmap_name: anylog-master-configmap
  # Allows running Kubernetes remotely. If commented out, code will ignore it
  node_selector: ""
image:
  # Image secret naming
  secret_name: imagepullsecret
  # (Docker Hub) Image Path
  repository: anylogco/anylog-network
  # Image version
  tag: beta-arm64
  # Image pulling policy
  pull_policy: IfNotPresent
  # whether to deploy AnyLog (prod) or a linux cli (bash) with AnyLog installed, but not running
  init_type: prod

volume:
  # Whether to enable volumes for AnyLog
  enable_volume: false

node_configs:
  general:
    # AnyLog License Key
    LICENSE_KEY: 4df552a98c6d7dbb178e828fd6947b1f3fee9911e03f37fe2106160465d9edba9eb34ca5b0c6b28a2e036dd5ed4c1590d9ae74a099ff1208775e3f3de67e571058a0a2b816e7fc45e06f33cf250851ebbce80e8b60dab00da5c425941637e636285e6883ba299d7ac810411197e09e857ba906ef39ef2cd40910f019a3c44acf2023-12-01bGuest
    # Information regarding which AnyLog node configurations to enable. By default, even if everything is disabled, AnyLog starts TCP and REST connection protocols
    NODE_TYPE: master
    # Name of the AnyLog instance
    NODE_NAME: anylog-master
    # Owner of the Anylog instance
    COMPANY_NAME: New Company

  networking:
    # Port address used by AnyLog's TCP protocol to communicate with other nodes in the network
    ANYLOG_SERVER_PORT: 32408
    # Port address used by AnyLog's REST protocol
    ANYLOG_REST_PORT: 32409

  blockchain:
    # TCP connection information for Master Node
    LEDGER_CONN: '{{ .Values.metadata.service_name }}:32048'

  monitoring:
    # Whether to monitor the node or not
    MONITOR_NODES: true
    # Which node type to send monitoring information to
    MONITOR_NODE: query
    # Company node is associated with the monitor node
    MONITOR_NODE_COMPANY: New Company