apiVersion: v1
kind: ConfigMap
metadata:
  name: master-configurations
  labels:
    app: al-nvidia-master
data:
  NODE_TYPE: "master"
  NODE_NAME: "master-node"
  COMPANY_NAME: "AnyLog"
  #EXTERNAL_IP: <EXTERNAL IP>
  #LOCAL_IP: <LOCAL IP>
  ANYLOG_SERVER_PORT: "32048"
  ANYLOG_REST_PORT: "32049"
  MASTER_NODE: "127.0.0.1:32048"
  SYNC_TIME: "30 second"

  # User should update DB_USER credentials
  DB_TYPE: "psql"
  DB_IP: "postgres"
  DB_USER: "admin"
  DB_PORT: "5432"
  DEFAULT_DBMS: "test"

  MQTT_ENABLE: "false"
  DEPLOY_LOCAL_SCRIPT: "false"

---
apiVersion: v1
kind: Secret
metadata:
  name: master-secret-configurations
  labels:
    app: al-nvidia-master
data:
   DB_PASSWD: cGFzc3dkCg== # passwd | base64