apiVersion: v1
kind: Service
metadata:
  name: al-nvidia-master
  labels:
    app: al-nvidia-master
spec:
  type: NodePort
  ports:
  - name: al-nvidia-master-tcp
    protocol: TCP
    port: 32048
    targetPort: 32048
    nodePort: 32048
  - name: al-nvidia-master-rest
    protocol: TCP
    port: 32049
    targetPort: 32049
    nodePort: 32049
  selector:
    app: al-nvidia-master