version: "2.2"
services:
  anylog-query:
    image: anylogco/anylog-network:${TAG}
    env_file:
      - anylog_configs.env
      - advance_configs.env
    environment:
      - INIT_TYPE=${INIT_TYPE}
    container_name: anylog-query
    restart: always
    stdin_open: true
    tty: true
    ports:
      - ${ANYLOG_SERVER_PORT}:${ANYLOG_SERVER_PORT}
      - ${ANYLOG_REST_PORT}:${ANYLOG_REST_PORT}
    volumes:
      - anylog-query-anylog:/app/AnyLog-Network/anylog
      - anylog-query-blockchain:/app/AnyLog-Network/blockchain
      - anylog-query-data:/app/AnyLog-Network/data
      - anylog-query-local-scripts:/app/deployment-scripts
volumes:
  anylog-query-anylog:
  anylog-query-blockchain:
  anylog-query-data:
  anylog-query-local-scripts:
