version: "2.2"
services:
  anylog-query:
    image: anylogco/anylog-network:${BUILD}
    env_file:
      - anylog_configs.env
      - advance_configs.env
    environment:
      - NODE_TYPE: ${INIT_TYPE}
    container_name: anylog-query
    restart: always
    stdin_open: true
    tty: true
    network_mode: "host" 
    volumes:
      - anylog-query-anylog:/app/AnyLog-Network/anylog
      - anylog-query-blockchain:/app/AnyLog-Network/blockchain
      - anylog-query-data:/app/AnyLog-Network/data
      - anylog-query-local-scripts:/app/deployment-scripts
volumes:
  anylog-query-anylog:
  anylog-query-blockchain:
  anylog-query-data:
  anylog-query-local-scripts:
