version: "2.2"
services:
  anylog-query:
    image: anylogco/anylog-network:${TAG}
    privileged: true
    env_file:
      - anylog_configs.env
      - advance_configs.env
    environment:
      - INIT_TYPE=${INIT_TYPE}
    container_name: anylog-query
    restart: always
    stdin_open: true
    tty: true
    network_mode: host
#    ports:
#      - ${ANYLOG_SERVER_PORT}:${ANYLOG_SERVER_PORT}
#      - ${ANYLOG_REST_PORT}:${ANYLOG_REST_PORT}
    volumes:
      - anylog-query-anylog:/app/AnyLog-Network/anylog
      - anylog-query-blockchain:/app/AnyLog-Network/blockchain
      - anylog-query-data:/app/AnyLog-Network/data
      - anylog-query-local-scripts:/app/deployment-scripts
      - ${NEBULA_CONFIG_FILE}:${ANYLOG_PATH}/nebula/config.yml
      - anylog-query-nebula:${ANYLOG_PATH}/nebula/
volumes:
  anylog-query-anylog:
  anylog-query-blockchain:
  anylog-query-data:
  anylog-query-local-scripts:
  anylog-query:
