apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f /home/anylog/docker-compose/docker-compose-update.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: anylog-gui
  name: anylog-gui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: anylog-gui
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f /home/anylog/docker-compose/docker-compose-update.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: anylog-gui
    spec:
      containers:
        - env:
            - name: CONFIG_FILE
              value: testnet.json
            - name: CONFIG_FOLDER
              value: views
            - name: CONN_IP
              value: 0.0.0.0
            - name: GUI_PORT
              value: "5000"
          image: anylogco/anylog-gui:latest
          name: anylog-gui
          ports:
            - containerPort: 5000
          resources: {}
          stdin: true
          tty: true
      restartPolicy: Always
status: {}
