apiVersion: v1
kind: ConfigMap
metadata:
  name: node-configuration
  labels:
    app: anylog-node
data:
  NODE_TYPE: "single-node"
  NODE_NAME: "anylog-node"
  COMPANY_NAME: "AnyLog"
  #EXTERNAL_IP: <EXTERNAL IP>
  #LOCAL_IP: <LOCAL IP>
  ANYLOG_SERVER_PORT: "${ANYLOG_SERVER_PORT}"
  ANYLOG_REST_PORT: "${ANYLOG_REST_PORT}"
  ANYLOG_BROKER_PORT: "${ANYLOG_BROKER_PORT}"
  MASTER_NODE: "127.0.0.1:${ANYLOG_SERVER_PORT}"
  SYNC_TIME: "30 second"

  # User should update DB_USER credentials
  DB_TYPE: "psql"
  DB_IP: "127.0.0.1"
  DB_USER: "admin"
  DB_PASSWD: "passwd"
  DB_IP: "postgres"
  DB_PORT: "5432"
  DEFAULT_DBMS: "test"

  CLUTSER_NAME: "new-cluster"
  ENABLE_PARTITION: "true"
  PARTITION_COLUMN: "timestamp"
  PARTITION_INTERVAL: "7 days"
  PARTITION_KEEP: "42"
  ENABLE_DATA_MONITOR: "false"
  TABLE_NAME: "*"
  INTERVAL_VALUE: "10"
  DATA_MONITOR_INTERVAL: "1 minute"
  DATA_MONITOR_COLUMN: "value"

  MQTT_ENABLE: "false"
  BROKER: "driver.cloudmqtt.com"
  MQTT_PORT: "18785"
  MQTT_USER: "ibglowct"
  MQTT_PASSWORD: "MSY4e009J7ts"
  MQTT_LOG: "false"
  MQTT_TOPIC_NAME: "anylogedgex"
  MQTT_TOPIC_DBMS: "test"
  MQTT_TOPIC_TABLE: "bring [device]"
  MQTT_COLUMN_TIMESTAMP: "now"
  MQTT_COLUMN_VALUE_TYPE: "float"
  MQTT_COLUMN_VALUE: "bring [readings][][value]"

---
apiVersion: v1
kind: Service
metadata:
  name: anylog-node
  labels:
    app: anylog-node
spec:
  ports:
  - port: ${ANYLOG_SERVER_PORT}
    name: anylog-node-tcp
  - port: ${ANYLOG_REST_PORT}
    name: anylog-node-rest
  - port: ${ANYLOG_BROKER_PORT}
    name: anylog-node-broker
  selector:
    app: anylog-node
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: anylog-node
  labels:
    app: anylog-node
spec:
  serviceName: "anylog-node"
  replicas: 1
  selector:
    matchLabels:
      app: anylog-node
  template:
    metadata:
      labels:
        app: anylog-node
    spec:
      imagePullSecrets:
      - name: anylogregistrykey
      containers:
      - name: anylog-node
        image: anylogco/anylog-network:test
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: node-configuration
        ports:
          - containerPort: ${ANYLOG_SERVER_PORT}
            name: tcp
          - containerPort: ${ANYLOG_REST_PORT}
            name: rest
          - containerPort: ${ANYLOG_BROKER_PORT}
            name: broker
        volumeMounts:
        - name: anylog-node-anylog-pv-data
          mountPath: /app/AnyLog-Network/anylog
        - name: anylog-node-blockchaiin-pv-data
          mountPath: /app/AnyLog-Network/blockchaiin
        - name: anylog-node-data-pv-data
          mountPath: /app/AnyLog-Network/data
        - name: anylog-node-local-scripts-pv-data
          mountPath: /app/AnyLog-Network/local-scripts
      volumes:
      - name: anylog-node-anylog-pv-data
        persistentVolumeClaim:
          claimName: anylog-node-anylog-pv-claim
      - name: anylog-node-blockchain-pv-data
        persistentVolumeClaim:
          claimName: anylog-node-blockchain-pv-claim
      - name: anylog-node-data-pv-data
        persistentVolumeClaim:
          claimName: anylog-node-data-pv-claim
      - name: anylog-node-local-scripts-pv-data
        persistentVolumeClaim:
          claimName: anylog-node-local-scripts-pv-claim

