apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f /home/anylog/docker-compose/docker-compose-update.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: anylog-node
  name: anylog-node
spec:
  ports:
    - name: "13480"
      port: 13480
      targetPort: 13480
    - name: "13481"
      port: 13481
      targetPort: 13481
    - name: "13482"
      port: 13482
      targetPort: 13482
  selector:
    io.kompose.service: anylog-node
status:
  loadBalancer: {}
