apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f /home/anylog/docker-compose/docker-compose-update.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: grafana
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f /home/anylog/docker-compose/docker-compose-update.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/frontend: "true"
        io.kompose.service: grafana
    spec:
      containers:
        - env:
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_DISABLE_LOGIN_FORM
              value: "false"
            - name: GF_INSTALL_PLUGINS
              value: simpod-json-datasource,grafana-worldmap-panel
            - name: GF_SECURITY_ALLOW_EMBEDDING
              value: "true"
            - name: GRAFANA_ADMIN_PASSWORD
              value: passwd
            - name: GRAFANA_ADMIN_USER
              value: admin
          image: grafana/grafana:7.5.7
          name: grafana
          ports:
            - containerPort: 3000
          resources: {}
          stdin: true
          tty: true
      restartPolicy: Always
status: {}
