kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: localstorage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer


---
# Postgres PersistentVolume
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv
spec:
  storageClassName: localstorage
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    name: postgres-pv-claim
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/mnt/postgres/data"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              - postgres
---
# Postgres PersistentVolumeClaim
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres
spec:
  storageClassName: localstorage
  volumeName: postgres-pv
  capacity:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi