apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f /home/anylog/docker-compose/docker-compose-update.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: remote-cli
  name: remote-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: remote-cli
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f /home/anylog/docker-compose/docker-compose-update.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/frontend: "true"
        io.kompose.service: remote-cli
    spec:
      containers:
        - env:
            - name: CONN_IP
              value: 0.0.0.0
            - name: CONN_PORT
              value: "8000"
          image: anylogco/remote-cli:latest
          name: remote-cli
          ports:
            - containerPort: 8000
          resources: {}
          stdin: true
          tty: true
      restartPolicy: Always
status: {}
