apiVersion: v1
kind: ConfigMap
metadata:
  name: cli-configuration
  labels:
    app: remote-cli
data:
  CONN_IP: "0.0.0.0"
  CLI_PORT: "${CLI_PORT}"

---
apiVersion: v1
kind: Service
metadata:
  name: remote-cli
  labels:
    app: remote-cli
spec:
  ports:
  - port: ${CLI_PORT}
    name: remote-cli
  selector:
    app: remote-cli
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: remote-cli
  labels:
    app: remote-cli
spec:
  serviceName: "remote-cli"
  replicas: 1
  selector:
    matchLabels:
      app: remote-cli
  template:
    metadata:
      labels:
        app: remote-cli
    spec:
      containers:
      - name: remote-cli
        image: anylogco/remote-cli:latest
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: cli-configuration
        ports:
          - containerPort: ${CLI_PORT}
            name: remote-cli
#        volumeMounts:
#        - name: cli-pv-data
#          mountPath: /app/Remote-CLI/anylog_query/static/json
#      volumes:
#      - name: cli-pv-data
#        persistentVolumeClaim:
#          claimName: cli-pv-claim


