# Postgres
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv
  labels:
    app: postgres
    type: local
spec:
  storageClassName: microk8s-hostpath
  claimRef:
    name: postgres-pv-claim
#    namespace: postgres
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/postgres/data"
---
# Grafana
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
#  namespace: postgres
  labels:
    app: postgres
spec:
  storageClassName: microk8s-hostpath
  volumeName: postgres-pv
  capacity:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: grafana-pv
  labels:
    app: grafana
    type: local
spec:
  storageClassName: microk8s-hostpath
  claimRef:
    name: grafana-pv-claim
#    namespace: grafana
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/grafana/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-pv-claim
#  namespace: grafana
  labels:
    app: grafana
spec:
  storageClassName: microk8s-hostpath
  volumeName: grafana-pv
  capacity:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
