apiVersion: v1
kind: Service
metadata:
  namespace: '{{ .Values.general.namespace }}'
  name: remote-cli-svs
  labels:
    app: '{{ .Values.general.app_name }}'
spec:
  type: NodePort
  ports:
  - name: '{{ .Values.networking.port_name }}'
    protocol: TCP
    appProtocol: http
    port: 31800
    targetPort: 31800
    nodePort: 31800
  selector:
    app: '{{ .Values.general.app_name }}'
