apiVersion: apps/v1
kind: Deployment
metadata:
  name: al-nvidia-master
  labels:
    app: al-nvidia-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: al-nvidia-master
  template:
    metadata:
      labels:
        app: al-nvidia-master
    spec:
      imagePullSecrets:
      - name: imagepullsecret
      containers:
      - name: al-nvidia-master
        image: nvcr.io/uazwwnrnci5h/anylog/anylog-network:demo
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: master-configurations
        env:
          - name: DB_PASSWD
            valueFrom:
              secretKeyRef:
                name: master-secret-configurations
                key: DB_PASSWD
        ports:
          - containerPort: 32048
            name: tcp
          - containerPort: 32049
            name: rest