apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.general.name }}-configuration
  labels:
    app: {{ .Values.general.name }}
data:
  POSTGRES_USER: {{ .Values.credentials.POSTGRES_USER }}
  PGPORT: {{ .Values.networking.port | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.general.name }}-secret-configs
  labels:
    app: {{ .Values.general.name }}
data:
  POSTGRES_PASSWORD: {{ .Values.credentials.POSTGRES_PASSWORD }}
