apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.general.name }}
  labels:
    app: {{ .Values.general.name }}
spec:
  replicas: {{ .Values.general.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.general.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.general.name }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.image.secretName }}
      containers:
      - name: {{ .Values.general.name }}
        image: {{ .Values.image.name }}:{{ .Values.image.version }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: {{ .Values.general.name }}-configuration
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.general.name }}-secret-configs
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: {{ .Values.networking.port }}
          name: {{ .Values.general.name }}-port