apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type: ClusterPort
  ports:
  - name: postgres-tcp
    protocol: TCP
    port: 5432
  selector:
    app: postgres