apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.general.name }}
  labels:
    app: {{ .Values.general.name }}
spec:
  ports:
  - port: 5432
    name: {{ .Values.general.name }}-port
  selector:
    app: {{ .Values.general.name }}
