kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv
  labels:
    app: '{{ .Values.general.app_name }}'
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/anylog/postgres"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    app: '{{ .Values.general.app_name }}'
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100M
