kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: my-local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
---
kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: '{{ .Values.general.namespace }}'
  name: postgres-pv
  labels:
    type: local
spec:
  storageClassName: my-local-storage
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/postgres/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: '{{ .Values.general.namespace }}'
  name: postgres-pv-claim
  labels:
    app: '{{ .Values.general.app_name }}'
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100M
