apiVersion: v1
kind: ConfigMap
metadata:
  namespace: '{{ .Values.general.namespace }}'
  name: '{{ .Values.general.configmap_name }}'
  labels:
    app: '{{ .Values.general.app_name }}'
data:
  GF_PORT: '{{ .Values.networking.port }}'
  GRAFANA_ADMIN_USER: '{{ .Values.configs.user }}'
  GRAFANA_ADMIN_PASSWORD: '{{ .Values.configs.password }}'
  GF_AUTH_DISABLE_LOGIN_FORM: '{{ .Values.configs.disable_login_form }}'
  GF_AUTH_ANONYMOUS_ENABLED: '{{ .Values.configs.anonymous_enabled }}'
  GF_SECURITY_ALLOW_EMBEDDING: '{{ .Values.configs.embedding }}'
  GF_INSTALL_PLUGINS: '{{ .Values.configs.plugins }}'

