# Based On: https://medium.com/@suyashmohan/setting-up-postgresql-database-on-kubernetes-24a2a192e962
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-configuration
  labels:
    app: grafana
data:
  GRAFANA_ADMIN_USER: admin
  GRAFANA_ADMIN_PASSWORD: admin
  GF_AUTH_DISABLE_LOGIN_FORM: "false"
  GF_AUTH_ANONYMOUS_ENABLED: "true"
  GF_SECURITY_ALLOW_EMBEDDING: "true"
  GF_INSTALL_PLUGINS: simpod-json-datasource,grafana-worldmap-panel
  #GF_SERVER_HTTP_ADDRESS: 10.0.0.219
  #GF_SERVER_HTTP_PORT: "31000"
