#volumes:
#      - grafana-data:/var/lib/grafana
#      - grafana-log:/var/log/grafana
#      - grafana-config:/etc/grafana

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.general.volume_name }}-claim
spec:
  storageClassName: {{ .Values.spec.storage_class }}
  accessModes:
    - {{ .Values.spec.access_mode }}
  resources:
    requests:
      storage: {{ .Values.spec.storage_size }}
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Values.general.volume_name }}
spec:
  storageClassName: {{ .Values.spec.storage_class }}
  capacity:
    storage: {{ .Values.spec.storage_size }}
  accessModes:
    - {{ .Values.spec.access_mode }}
  persistentVolumeReclaimPolicy: {{ .Values.spec.retain_policy }}
  hostPath:
    path: {{ .Values.spec.host_path }}
