apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: '{{ .Values.general.namespace }}'
  name: '{{ .Values.general.deployment_name }}'
  labels:
    app: '{{ .Values.general.app_name }}'
spec:
  template:
    metadata:
      labels:
        app: '{{ .Values.general.app_name }}'
      spec:
        securityContext:
          fsGroup: 472
          supplementalGroup:
            - 0
      containers:
        - name: grafana
          image: grafana/grafana:7.5.7
          imagePullPolicy: IfNotPresent
          ports:
            - name: '{{ .Values.networking.port_name }}
              containerPort: 3000
          {{- if eq .Values.volume.enable_volume true }}
          volumeMounts:
            - name: {{ .Values.volume.volume_name }}
              persistentVolumeClaim:
                claimName: {{ .Values.volume.volume_name }}-claim
          {{ end }}
      {{- if eq .Values.volume.enable_volume true }}
      volumes:
        - name: {{ .Values.volume.volume_name }}
        persistentVolumeClaim:
          claimName: {{ .Values.volume.volume_name }}-claim
      {{ end }}


