apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: '{{ .Values.general.namespace }}'
  name: '{{ .Values.general.deployment_name }}'
  labels:
    app: '{{ .Values.general.app_name }}'
spec:
  replicas: {{ .Values.general.replicas }}
  selector:
    matchLabels:
      app: '{{ .Values.general.app_name }}'
  template:
    metadata:
      name: '{{ .Values.general.deployment_name }}'
      labels:
        app: {{ .Values.general.app_name }}
    spec:
      containers:
      - name: '{{ .Values.general.deployment_name }}'
        image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
        envFrom:
          - configMapRef:
              name: '{{ .Values.general.configmap_name }}'
        ports:
        - name: '{{ .Values.networking.port_name }}'
          containerPort: 3000
        {{- if eq .Values.volume.enable_volume true }}
        volumeMounts:
          - name: {{ .Values.volume.data_volume_name }}
            mountPath: /var/lib/grafana
#          - name: {{ .Values.volume.log_volume_name }}
#            mountPath: /var/log/grafana
#          - name: {{ .Values.volume.config_volume_name }}
#            mountPath: :/etc/grafana
        {{ end }}
      {{- if eq .Values.volume.enable_volume true }}
      volumes:
        - name: {{ .Values.volume.data_volume_name }}
          persistentVolumeClaim:
            claimName: {{ .Values.volume.data_volume_name }}-claim
#        - name: {{ .Values.volume.log_volume_name }}
#          persistentVolumeClaim:
#            claimName: {{ .Values.volume.log_volume_name }}-claim
#        - name: {{ .Values.volume.config_volume_name }}
#          persistentVolumeClaim:
#            claimName: {{ .Values.volume.config_volume_name }}-claim
      {{ end }}
