apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  type: NodePort
  ports:
  - name: grafana-tcp
    protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 32000
  selector:
    app: grafana