apiVersion: v1
kind: Service
metadata:
  namespace: '{{ .Values.general.namespace }}'
  name: '{{ .Values.general.service_name }}'
  labels:
    app: '{{ .Values.general.app_name }}'
spec:
  selector: 
    app: '{{ .Values.general.app_name }}'
  type: NodePort  
  ports:
    - name: '{{ .Values.networking.port_name }}'
      protocol: TCP
      appProtocol: http
      port: 3000
      targetPort: 3000
      nodePort: {{ .Values.networking.node_port }}