apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: grafana
  name: grafana-external
spec:
  type: NodePort
  ports: 
  - name: grafana-service
    appProtocol: http
    port: 3000
    targetPort: 3000
    nodePort: 31000
status:
  loadBalancer: {}
