version: '3.3'
services:
  db:
    image: mysql:8.0
    restart: always
    env_file:
      - mysql.env
    container_name: mysql
    stdin_open: true
    tty: true
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mydb:/var/lib/mysql
volumes:
  mydb: