version: "2.2"
services:
  anylog-publisher:
    image: anylogco/anylog-network:${TAG}
    privileged: true
    restart: always
    env_file:
      - anylog_configs.env
      - advance_configs.env
    container_name: ${CONTAINER_NAME}
    stdin_open: true
    tty: true
    network_mode: host
    environment:
      - INIT_TYPE=${INIT_TYPE}
    volumes:
      - anylog-publisher-anylog:/app/AnyLog-Network/anylog
      - anylog-publisher-blockchain:/app/AnyLog-Network/blockchain
      - anylog-publisher-data:/app/AnyLog-Network/data
      - anylog-publisher-local-scripts:/app/deployment-scripts
      - nebula-configs:${ANYLOG_PATH}/nebula/
volumes:
  anylog-publisher-anylog:
  anylog-publisher-blockchain:
  anylog-publisher-data:
  anylog-publisher-local-scripts:
  nebula-configs: