version: "2.2"
services:
  anylog-publisher:
    image: anylogco/anylog-network:${BUILD}
    env_file:
      - anylog_configs.env
      - advance_configs.env
    environment:
      - NODE_TYPE: ${INIT_TYPE}
    container_name: ${CONTAINER_NAME}
    restart: always
    stdin_open: true
    tty: true
    network_mode: "${NETWORK}"
    volumes:
      - anylog-publisher-anylog:/app/AnyLog-Network/anylog
      - anylog-publisher-blockchain:/app/AnyLog-Network/blockchain
      - anylog-publisher-data:/app/AnyLog-Network/data
      - anylog-publisher-local-scripts:/app/deployment-scripts
volumes:
  anylog-publisher-anylog:
  anylog-publisher-blockchain:
  anylog-publisher-data:
  anylog-publisher-local-scripts:
