general:
  namespace: default
  app_name: grafana
  deployment_name: grafana-app
  service_name: grafana-svs
  configmap_name: grafana-configs
  replicas: 1

volume:
  enable_volume: true
  data_volume_name: grafana-data
  log_volume_name: grafana-log
  config_volume_name: grafana-config

image:
  repository: grafana/grafana
  tag: 7.5.7
  pullPolicy: Always

networking:
  port_name: grafana-port
  node_port: 31000

configs:
  username: admin
  password: admin
  disable_login_form: false
  enable_anonymous: true
  enable_embedding: true
  plugins: [
      simpod-json-datasource,
      grafana-worldmap-panel
  ]
  ini_file:
    disable_login_form: false
    enabled: true
    allow_embedding: true

