apiVersion: v1
kind: ConfigMap
metadata:
  namespace: '{{ .Values.metadata.namespace }}'
  name: '{{ .Values.metadata.configmap_name }}'
  labels:
    app: '{{ .Values.metadata.app_name }}'
data:
  # Minikube IP address
  KUBE_APISERVER_IP: '{{ .Values.node_configs.kubernetes.ip }}'
  NGINX_PORT: '{{ .Values.node_configs.nginx.nginx_port }}'
  ANYLOG_SERVER_PORT: '{{ .Values.node_configs.networking.ANYLOG_SERVER_PORT }}'
  ANYLOG_REST_PORT: '{{ .Values.node_configs.networking.ANYLOG_REST_PORT }}'
  {{ if ne .Values.node_configs.networking.ANYLOG_BROKER_PORT "" }}
  ANYLOG_BROKER_PORT: '{{ .Values.node_configs.networking.ANYLOG_BROKER_PORT }}'
  {{ end }}
  nginx.conf: |- 
    {{ tpl (.Files.Get "nginx/nginx.conf") . | nindent 2 }}
  anylog.conf: |-
    {{ tpl (.Files.Get "nginx/sites-enabled/anylog.conf") . | nindent 2 }}
