apiVersion: v1
kind: Service
metadata:
  namespace: '{{ .Values.metadata.namespace }}'
  name: '{{ .Values.metadata.deployment_name }}'
  labels:
    app: '{{ .Values.metadata.app_name }}'
spec:
  replicas: '{{ .Values.metadata.replicas }}'
  selector:
    matchLabels:
      app: '{{ .Values.metadata.app_name }}'
  type: NodePort
  ports:
    - protocol: TCP
      port: '{{ .Values.node_configs.nginx.nginx_port }}'
      targetPort: '{{ .Values.node_configs.nginx.nginx_port }}'
      nodePort: '{{ .Values.node_configs.nginx.node_port }}'
