general:
  name: anylog
  replicas: 1

image:
  set_secret: true
  secretName: imagepullsecret
  name: anylogco/anylog-network
  version: develop
  pullPolicy: IfNotPresent

configs:
  basic:
    node_type: "rest"
    node_name: "anylog-node"
    company: "new company"

  networking:
    services:
      anylog_server_port: 32048
      anylog_rest_port: 32049
      anylog_broker_port: 32050
    network_ips:
      external_ip: ""
      local_ip: ""
    settings:
      master_node: "127.0.0.1:2048"
      enable_broker: "false"
