general:
#  namespace: anylog-network
  name: remote-cli
  replicas: 1

image:
  secretName: imagepullsecret
  name: uazwwnrnci5h/anylog/remote-cli
  version: 1.0.0
  pullPolicy: IfNotPresent

configs:
  ip: "0.0.0.0"
  port: 31800
