apiVersion: v1
kind: Pod
metadata:
  name: wordpress-mysql-pod
  labels:
    app: wordpress
spec:
  containers:
  - image: mysql:5.6
    name: mysql
    volumeMounts:
    - name: mysql-persistent-storage
      mountPath: /var/lib/mysql
  volumes:
  - name: mysql-persistent-storage
    hostPath:
      - path: /data
      type: DirectoryOrCreate

