version: "3.4"
services:
  database:
    image: postgres:14.0-alpine
    env_file:
      - envs/postgres.env
    container_name: postgres
    stdin_open: true
    tty: true
    networks:
      - frontend
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
#
#  grafana:
#    image: grafana/grafana:7.5.7
#    env_file:
#      - envs/grafana.env
#    container_name: grafana
#    stdin_open: true
#    tty: true
#    networks:
#      - frontend
#    ports:
#      - "3000:3000"
#    volumes:
#      - grafana-data:/var/lib/grafana
#      - grafana-log:/var/log/grafana
#      - grafana-config:/etc/grafana
#
  remote-cli:
    image: anylogco/remote-cli:latest
    env_file:
      - envs/anylog_tools.env
    container_name: remote-cli
    stdin_open: true
    tty: true
    networks:
      - frontend
    ports:
      - 8000:8000
    volumes:
      - remote-cli:/app/Remote-CLI/anylog_query/static/json
  anylog-gui:
    image: anylogco/anylog-gui:latest
    container_name: anylog-gui
    env_file:
      - envs/anylog_tools.env
    stdin_open: true
    tty: true
    ports:
      - 5000:5000
    volumes:
      - anylog-gui:/app/AnyLog-GUI/views
  anylog-node:
    image: anylogco/anylog-network:aarna
    env_file:
      - envs/anylog_node.env
    container_name: anylog-node
    stdin_open: true
    tty: true
    network_mode: host
    ports:
      - 32048:32048
      - 32049:32049
      - 32050:32050
    volumes:
      - anylog-node-anylog:/app/AnyLog-Network/anylog
      - anylog-node-blockchain:/app/AnyLog-Network/blockchain
      - anylog-node-data:/app/AnyLog-Network/data
      - anylog-node-scripts:/app/AnyLog-Network/scripts
networks:
  frontend:
    driver: bridge
    external: false
volumes:
  pgdata:
  grafana-data:
  grafana-log:
  grafana-config:
  remote-cli:
  anylog-gui:
  anylog-node-anylog:
  anylog-node-blockchain:
  anylog-node-data:
  anylog-node-scripts:
