apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  namespace: {{ .Values.general.namespace }}
  name: {{ .Values.general.credentials_name }}
  labels:
    app: {{ .Values.general.app_name }}
spec:
    replicas: {{ .Values.general.replicas }}
    selector:
        matchLabels:
            app: {{ .Values.general.app_name }}
    strategy: {}

