apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.general.namespace }}
  name: {{ .Values.general.deployment_name }}
  labels:
    app: {{ .Values.general.app_name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
