apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.general.namespace }}
  name: {{ .Values.general.service_name }}
  labels:
    app: {{ .Values.general.app_name }}
spec:
  type: ClusterIP
  ports:
  - name: '{{ .Values.networking.name }}'
    port: {{ .Values.networking.port }}
    targetPort: {{ .Values.networking.port }}
  - protocol: '{{ .Values.networking.name }}-express'
    port: {{ .Values.networking.express_port }}
    targetPort: {{ .Values.networking.express_port }}
  selector:
    app: '{{ .Values.general.app_name }}'

