general:
  namespace: default
  name: remote-cli
  application: remote-cli
  replicas: 1

image:
  secretName: ""
  name: anylogco/remote-cli
  version: latest
  pullPolicy: IfNotPresent

configs:
  ip: "0.0.0.0"
  port: 31800