apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.general.configmap_name }}
  labels:
    app: {{ .Values.general.app_name }}
data:
  CONN_IP: {{ .Values.networking.ip }}
  CLI_PORT: {{ .Values.networking.port | quote }}
