apiVersion: v1
kind: ConfigMap
metadata:
  namesapce: {{ default .Values.general.namespace "default" }}
  name: {{ default .Values.general.name "remote-cli" }}-configuration
  labels:
    app: {{ default .Values.general.application "remote-cli" }}
data:
  CONN_IP: {{ .Values.configs.ip }}
  CLI_PORT: {{ default .Values.configs.port "31800" | quote }}
