apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ default .Values.general.namespace "default" }}
  name: {{ default .Values.general.configmap_name "remote-cli-configs" }}
  labels:
    app: {{ default .Values.general.app_name "remote-cli"}}
data:
  CONN_IP: {{ default .Values.networking.ip "0.0.0.0" }}
  CLI_PORT: {{ default .Values.networking.port 31800 |quote }}
