apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.general.name }}-configuration
  labels:
    app: remote-cli
data:
  CONN_IP: {{ .Values.configs.ip }}
  CLI_PORT: {{ .Values.configs.port |quote }}
