apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ default .Values.general.namespace "default" }}
  name: {{ default .Values.general.deployment_name "remote-cli-app" }}
  labels:
    app: {{ default .Values.general.app_name "remote-cli"}}
spec:
  replicas: {{ default .Values.general.replicas 1 }}
  selector:
    matchLabels:
      app: {{ default .Values.general.app_name "remote-cli"}}
  template:
    metadata:
      labels:
        app: {{ default .Values.general.app_name "remote-cli"}}
    spec:
      {{ if .Values.image.secretName }} and {{- if ne .Values.image.secretName "" }}
      imagePullSecrets:
        - name: {{ .Values.image.secretName }}
      {{ end }} {{ end }}
      containers:
      - name: {{ default .Values.general.deployment_name "remote-cli-app" }}
        image: {{ default .Values.image.name "anylogco/remote-cli"}}:{{ default .Values.image.version "latest" }}
        imagePullPolicy: {{ default .Values.image.pullPolicy "IfNotPresent" }}
        envFrom:
        - configMapRef:
            name: {{ default .Values.general.configmap_name "remote-cli-configs" }}
        ports:
        - containerPort: {{ default .Values.networking.port 31800 }}
          name: {{ default .Values.networking.port_name  "rmt-cli-port" }}
