apiVersion: apps/v1
kind: Deployment
metadata:
  namesapce: {{ default .Values.general.namespace "default" }}
  name: {{ default .Values.general.name "remote-cli" }}
  labels:
    app: {{ default .Values.general.application "remote-cli" }}
spec:
  replicas: {{ default .Values.general.replicas 1 }}
  selector:
    matchLabels:
      app: {{ default .Values.general.application "remote-cli" }}
  template:
    metadata:
      labels:
        app: {{ default .Values.general.application "remote-cli" }}
    spec:
      {{- if ne .Values.image.secretName "" }} 
      imagePullSecrets:
        - name: {{ .Values.image.secretName }}
      {{ end }} 
      containers:
      - name: {{ default .Values.general.name "remote-cli" }}
        image: {{ default .Values.image.name "anylogco/remote-cli" }}:{{ default .Values.image.version "latest" }}
        imagePullPolicy: {{ default .Values.image.pullPolicy "IfNotPresent" }}
        envFrom:
        - configMapRef:
            name: {{ default .Values.general.name "remote-cli" }}-configuration
        ports:
        - containerPort: {{ default .Values.configs.port 31800 }}
          name: {{ default .Values.general.name "remote-cli" }}
