apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.general.name }}
  labels:
    app: remote-cli
spec:
  replicas: {{ .Values.general.replicas }}
  selector:
    matchLabels:
      app: remote-cli
  template:
    metadata:
      labels:
        app: remote-cli
    spec:
      {{ if .Values.image.secretName }}
      imagePullSecrets:
        - name: {{ .Values.image.secretName }}
      {{ end }} 
      containers:
      - name: {{ .Values.general.name }}
        image: {{ .Values.image.name }}:{{ .Values.image.version }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: {{ .Values.general.name }}-configuration
        ports:
        - containerPort: {{ .Values.configs.port }}
          name: rmt-cli-conn
