apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: '{{ .Values.general.namespace }}'
  name: '{{ .Values.general.deployment_name }}'
  labels:
    app: '{{ .Values.general.app_name }}'
spec:
  replicas: {{ .Values.general.replicas }}
  selector:
    matchLabels:
      app: '{{ .Values.general.app_name }}'
  template:
    metadata:
      labels:
        app: {{ .Values.general.app_name }}
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
      - name: '{{ .Values.general.deployment_name }}'
        image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: '{{ .Values.general.configmap_name }}'
        ports:
        - name: '{{ .Values.networking.port_name }}'
          containerPort: {{ .Values.networking.port }}
        volumeMounts:
#          - name: remote-cli-json
#            mountPath: /app/Remote-CLI/anylog_query/static/json
          - name: remote-cli-blobs
            mountPath: /app/Remote-CLI/anylog_query/static/blobs/current/
      volumes:
#        - name: remote-cli-json
#          persistentVolumeClaim:
#            claimName: remote-cli-json-pvc
        - name: remote-cli-blobs
          persistentVolumeClaim:
            claimName: remote-cli-blobs-pvc