apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: '{{ .Values.general.namespace }}'
  name: '{{ .Values.general.deployment_name }}'
  labels:
    app: '{{ .Values.general.app_name }}'
spec:
  replicas: {{ .Values.general.replicas }}
  selector:
    matchLabels:
      app: '{{ .Values.general.app_name }}'
  template:
    metadata:
      labels:
        app: {{ .Values.general.app_name }}
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
      - name: '{{ .Values.general.deployment_name }}'
        image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: '{{ .Values.general.configmap_name }}'
        ports:
        - name: '{{ .Values.networking.port_name }}'
          containerPort: {{ .Values.networking.port }}
        {{- if eq .Values.volume.enable_volume true }}
        volumeMounts:
          - name: '{{ .Values.volume.json_volume }}' # grafana data volume
            mountPath: /app/Remote-CLI
        {{ end }}
      {{- if eq .Values.volume.enable_volume true }}
      volumes:
        - name: '{{ .Values.volume.json_volume }}'
          hostPath:
            path: /mnt/Remote-CLI
            type: DirectoryOrCreate
#        - name: '{{ .Values.volume.json_volume }}' # grafana data volume
#          persistentVolumeClaim:
#            claimName: '{{ .Values.volume.json_volume }}-pvc'
      {{ end }}