apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: '{{ .Values.general.namespace }}'
  name: '{{ .Values.general.deployment_name }}'
  labels:
    app: '{{ .Values.general.app_name }}'
spec:
  replicas: {{ .Values.general.replicas }}
  selector:
    matchLabels:
      app: '{{ .Values.general.app_name }}'
      version: '{{ .Values.image.tag }}'
  template:
    metadata:
      labels:
        app: {{ .Values.general.app_name }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.image.secretName }}
      containers:
      - name: '{{ .Values.general.deployment_name }}'
        image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: '{{ .Values.networking.port_name }}'
          containerPort: {{ .Values.networking.port }}

