apiVersion: v1
kind: Service
metadata:
    name: {{ .Values.general.name }}-service
    labels:
      app: {{ .Values.general.name }}
spec:
  type: NodePort
  ports:
    - name: {{ .Values.general.name }}
      port: {{ .Values.configs.port }}
      targetPort: {{ .Values.configs.port }}
      nodePort: {{ .Values.configs.port }}
  selector:
    app: {{ .Values.general.name }}

