apiVersion: v1
kind: Service
metadata:
    name: remote-cli-service
    labels:
      app: remote-cli
spec:
  type: NodePort
  ports:
    - name: remote-cli
      port: 31800
      targetPort: 31800
      nodePort: 31800

  selector:
    app: remote-cli-service

