apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.general.name }}-service
spec:
  selector:
    app: remote-cli
  type: NodePort
  ports:
    - name: rmt-cli-conn
      protocol: TCP
      appProtocol: http
      port: {{ .Values.configs.port |quote }}
      targetPort: {{ .Values.configs.port |quote }}
      nodePort: {{ .Values.configs.port |quote }}
