apiVersion: v1
kind: Service
metadata:
  name: {{ default .Values.general.name "remote-cli" }}-service
spec:
  selector:
    app: {{ default .Values.general.application "remote-cli" }}
  type: NodePort
  ports:
    - name: remote-cli
      protocol: TCP
      appProtocol: http
      port: {{ default .Values.configs.port 31800 }}
      targetPort: {{ default .Values.configs.port 31800 }}
      nodePort: {{ default .Values.configs.port 31800 }}
