apiVersion: v1
kind: Service
metadata:
  namespace: {{ default .Values.general.namespace "default" }}
  name: {{ default .Values.general.service_name "remote-cli-svs" }}
spec:
  selector:
    app: {{ default .Values.general.app_name "remote-cli"}}
  type: NodePort
  ports:
    - name: {{ default .Values.networking.port_name  "rmt-cli-port" }}
      protocol: TCP
      appProtocol: http
      port: {{ default .Values.networking.port  31800 }}
      targetPort: {{ default .Values.networking.port  31800 }}
      nodePort: {{ default .Values.networking.port  31800 }}
