apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.general.name }}-service
  #namespace: monitoring
spec:
  selector:
    app: {{ .Values.general.name }}
  type: NodePort
  ports:
    - name: remote-cli
      protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 31800
