version: "2.4"
services:
  database:
    image: postgres:14.0-alpine
    env_file:
      - envs/postgres.env
    container_name: postgres
    stdin_open: true
    tty: true
    networks:
      - frontend
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready"] 
      interval: 10s
      timeout: 5s
      retries: 5
  anylog-node:
    image: anylogco/anylog-network:aarna
    env_file:
      - envs/anylog_node.env
    container_name: anylog-node
    stdin_open: true
    tty: true
    network_mode: "host" 
    volumes:
      - anylog-node-anylog:/app/AnyLog-Network/anylog
      - anylog-node-blockchain:/app/AnyLog-Network/blockchain
      - anylog-node-data:/app/AnyLog-Network/data
      - anylog-node-local-scripts:/app/AnyLog-Network/scripts
    depends_on:
      database:
        condition: service_healthy
networks:
  frontend:
    driver: bridge
    external: false
volumes:
  pgdata:
  anylog-node-anylog:
  anylog-node-blockchain:
  anylog-node-data:
  anylog-node-local-scripts:
