apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.metadata.namespace }}
  name: remote-cli-blobs-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

