apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.general.namespace }}
  name: remote-cli-blobs-pvc
spec:
  accessModes:
    - {{ .Values.volume.access_mode }}
  resources:
    requests:
      storage: {{ .Values.volume.storage_size }}

