apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.metadata.namespace }}
  name: {{ .Values.volume.data_volume.name }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
