general:
  namespace: default
  app_name: postgres
  deployment_name: postgres-app
  service_name: postgres-svs
  configmap_name: postgres-configs
  volume_name: postgres-volume
  replicas: 1
  
image:
  repository: postgres
  tag: 14.0-alpine
  pullPolicy: IfNotPresent

volume:
  name: postgres-volume
  path: /var/lib/postgres
  accessMode: ReadWriteOnce
  storage: 20Gi

networking:
  name: psql-port
  port: 5432

credentials:
  username: admin
  password: demo
