general:
  #namespace: anylog-network
  name: postgres
  replicas: 1
image:
  set_secret: false
  secretName: imagepullsecret
  name: postgres
  version: 14.0-alpine
  pullPolicy: IfNotPresent
credentials:
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: ZGVtbwo= # demo | base64
