apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: '{{ .Values.metadata.namespace }}'
  name: tests-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
