apiVersion: v1
kind: ConfigMap
metadata:
  name: anylog-standalone-configuration
  labels:
    app: anylog-standalone-node
data:
  NODE_TYPE: "standalone"
  NODE_NAME: "anylog-standalone-node"
  COMPANY_NAME: "AnyLog"
  #EXTERNAL_IP: <EXTERNAL IP>
  #LOCAL_IP: <LOCAL IP>
  ANYLOG_SERVER_PORT: 32048
  ANYLOG_REST_PORT: 32049
#  ANYLOG_BROKER_PORT: 32050
  MASTER_NODE: "127.0.0.1:32048"
  SYNC_TIME: "30 second"

  # User should update DB_USER credentials
  DB_TYPE: "psql"
  DB_IP: "postgres"
  DB_USER: "admin"
  DB_PORT: 5432
  DEFAULT_DBMS: "test"

  CLUTSER_NAME: "cluster1"
  TABLE_NAME: "*"
  ENABLE_PARTITION: "true"
  PARTITION_COLUMN: "timestamp"
  PARTITION_INTERVAL: "14 days"
  PARTITION_KEEP: 6
  ENABLE_DATA_MONITOR: "false"

  MQTT_ENABLE: "true"
  BROKER: "driver.cloudmqtt.com"
  MQTT_PORT: 18785
  MQTT_USER: "ibglowct"
  MQTT_PASSWORD: "MSY4e009J7ts"
  MQTT_LOG: "false"
  MQTT_TOPIC_NAME: "anylogedgex"
  MQTT_TOPIC_DBMS: "test"
  MQTT_TOPIC_TABLE: "rand_int_generator" # default value should be - "bring [device]" (random_integer_generator01)
  MQTT_COLUMN_TIMESTAMP: "now"
  MQTT_COLUMN_VALUE_TYPE: "float"
  MQTT_COLUMN_VALUE: "bring [readings][][value]"

---
apiVersion: v1
kind: Secret
metadata:
  name: anylog-standalone-secret-configs
  labels:
    app: anylog
data:
  DB_PASSWD: ZGVtbwo= # demo | base64
  MQTT_PASSWORD: TVNZNGUwMDlKN3RzCg== # MSY4e009J7ts | base64
---
apiVersion: v1
kind: Service
metadata:
  name: anylog-standalone-node
  labels:
    app: anylog-standalone-node
spec:
  ports:
  - port: 32048
    name: anylog-standalone-node-tcp
  - port: 32049
    name: anylog-standalone-node-rest
  - port: 32050
    name: anylog-standalone-node-broker
  selector:
    app: anylog-standalone-node
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: anylog-standalone-node
  labels:
    app: anylog-standalone-node
spec:
  serviceName: "anylog-standalone-node"
  replicas: 1
  selector:
    matchLabels:
      app: anylog-standalone-node
  template:
    metadata:
      labels:
        app: anylog-standalone-node
    spec:
      imagePullSecrets:
      - name: anylog-registry-key
      containers:
      - name: anylog-standalone-node
        image: anylogco/anylog-network:AnyLog
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: node-configuration
        env:
          - name: DB_PASSWD
            valueForm:
              secretKeyRef:
                name: anylog-standalone-secret-configs
                key: DB_PASSWD
          - name: POSTGRES_PASSWORD
            valueForm:
              secretKeyRef:
                name: anylog-standalone-secret-configs
                key: POSTGRES_PASSWORD
        ports:
          - containerPort: 32048
            name: tcp
          - containerPort: 32049
            name: rest
          - containerPort: 32050
            name: broker
