apiVersion: apps/v1
kind: Deployment
metadata:
  name: anylog-standalone
  labels:
    app: anylog-standalone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anylog-standalone
  template:
    metadata:
      labels:
        app: anylog-standalone
    spec:
      imagePullSecrets:
      - name: imagepullsecret
      containers:
      - name: anylog-standalone
        image: nvcr.io/uazwwnrnci5h/anylog/anylog-network:demo
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: standalone-configurations
        ports:
          - containerPort: 32148
            name: standalone-tcp
          - containerPort: 32149
            name: standalone-rest