apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: '{{ .Values.metadata.namespace }}'
  name: '{{ .Values.metadata.deployment_name }}'
  labels:
    app: '{{ .Values.metadata.app_name }}'
spec:
  replicas: {{ .Values.metadata.replicas }}
  selector:
    matchLabels:
      app: '{{ .Values.metadata.app_name }}'
  template:
    metadata:
      labels:
        app: '{{ .Values.metadata.app_name }}'
    spec:
      hostname: '{{ .Values.metadata.pod_name }}'
      {{- if ne .Values.metadata.node_selector "" }}
      nodeSelector:
        kubernetes.io/hostname: '{{ .Values.metadata.node_selector }}'
      {{ end }}
      {{- if ne .Values.image.secret_name "" }}
      imagePullSecrets:
        - name: '{{ .Values.image.secret_name }}'
      {{ end }}
      containers:
      - name: '{{ .Values.metadata.deployment_name }}'
        image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
        imagePullPolicy: '{{ .Values.image.pull_policy }}'
         {{- if eq .Values.volume.enable_volume true }}
         volumeMounts:
           - name: '{{ .Values.metadata.pod_name }}-data'
             mountPath: /app/AnyLog-Network/data
           - name: '{{ .Values.metadata.pod_name }}-anylog'
             mountPath: /app/AnyLog-Network/anylog
           - name: '{{ .Values.metadata.pod_name }}-blockchain'
             mountPath: /app/AnyLog-Network/blockchain
         {{ end }}
        envFrom:
        - configMapRef:
            name: '{{ .Values.metadata.configmap_name }}'
        tty: true
        stdin: true
        ports:
        - name: server
          containerPort: {{ .Values.node_configs.networking.ANYLOG_SERVER_PORT }}
        - name: rest
          containerPort: {{ .Values.node_configs.networking.ANYLOG_REST_PORT }}
        {{- if .Values.node_configs.networking.ANYLOG_BROKER_PORT }}
        - name: broker
          containerPort: {{ .Values.node_configs.networking.ANYLOG_BROKER_PORT }}
        {{ end }}
       {{- if eq .Values.volume.enable_volume true }}
       volumes:
       - name: '{{ .Values.metadata.pod_name }}-data'
         persistentVolumeClaim:
          claimName: '{{ .Values.metadata.pod_name }}-data-pvc'
       - name: '{{ .Values.metadata.pod_name }}-anylog'
         persistentVolumeClaim:
          claimName: '{{ .Values.metadata.pod_name }}-anylog-pvc'
#       - name: '{{ .Values.metadata.pod_name }}-blockchain'
#         persistentVolumeClaim:
#           claimName: '{{ .Values.metadata.pod_name }}-blockchain-pvc'
       {{ end }}
