{{- if and (eq .Values.image.pull_info.api "") (eq .Values.image.pull_info.password "") }}
{{- fail "Both API key and password are empty. Please provide at least one of them." }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  namespace: '{{ .Values.metadata.namespace }}'
  name: '{{ .Values.image.secret_name }}'
type: Opaque
data:
  username: '{{ .Values.image.pull_info.username }}'  # Base64-encoded username
  password: '{{ .Values.image.pull_info.password }}'  # Base64-encoded password
  api-key: '{{ .Values.image.pull_info.api }}'  # Base64-encoded API key
