apiVersion: v1
kind: ConfigMap
metadata:
  name: operator1-node-configuration
  labels:
    app: anylog-operator1
data:
  NODE_TYPE: "operator"
  NODE_NAME: "operator-node1"
  COMPANY_NAME: "AnyLog"
  #EXTERNAL_IP: <EXTERNAL IP>
  #LOCAL_IP: <LOCAL IP>
  ANYLOG_SERVER_PORT: "32148"
  ANYLOG_REST_PORT: "32149"
  operator_NODE: "100.115.6.112:32148"
  SYNC_TIME: "30 second"

  # User should update DB_USER credentials
  DB_TYPE: "psql"
  DB_IP: "postgres"
  DB_USER: "admin"
  DB_PASSWD: "demo"
  DB_PORT: "5432"
  DEFAULT_DBMS: "test"

  # NEW_CLUSTER -- cluster name
  CLUSTER_NAME: "demo-cluster1"
  TABLE_NAME: "*"
  ENABLE_PARTITION: "true"
  PARTITION_COLUMN: "timestamp"
  PARTITION_INTERVAL: "14 days"
  PARTITION_KEEP: "6"
  ENABLE_DATA_MONITOR: "false"

  MQTT_ENABLE: "true"
  BROKER: "driver.cloudmqtt.com"
  MQTT_PORT: "18785"
  MQTT_USER: "ibglowct"
  MQTT_PASSWORD: "MSY4e009J7ts"
  MQTT_LOG: "false"
  MQTT_TOPIC_NAME: "anylogedgex"
  MQTT_TOPIC_DBMS: "test"
  # original value was "bring [device]" (Random-Integer-Generator01). howerver, due to a PSQL table name limit size is 65 chars, it's manually changeds to: rand_int
  MQTT_TOPIC_TABLE: "rand_data"
  MQTT_COLUMN_TIMESTAMP: "now"
  MQTT_COLUMN_VALUE_TYPE: "float"
  MQTT_COLUMN_VALUE: "bring [readings][][value]"

  DEPLOY_LOCAL_SCRIPT: "false"

---
apiVersion: v1
kind: Service
metadata:
  name: anylog-operator1
  labels:
    app: anylog-operator1
spec:
  type: NodePort
  ports:
  - name: anylog-operator1-tcp
    protocol: TCP
    port: 32048
    targetPort: 32048
    nodePort: 32048
  - name: anylog-operator1-rest
    protocol: TCP
    port: 32049
    targetPort: 32049
    nodePort: 32049
  selector:
    app: anylog-operator1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: anylog-operator1
  labels:
    app: anylog-operator1
spec:
  serviceName: "anylog-operator1"
  replicas: 1
  selector:
    matchLabels:
      app: anylog-operator1
  template:
    metadata:
      labels:
        app: anylog-operator1
    spec:
      imagePullSecrets:
      - name: imagepullsecret
      containers:
      - name: anylog-operator1
        image: anylogco/anylog-network:develop
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: operator1-node-configuration
        ports:
          - containerPort: 32148
            name: tcp
          - containerPort: 32149
            name: rest
          - containerPort: 32150
            name: broker
