apiVersion: v1
kind: ConfigMap
metadata:
  name: publisher-configurations
  labels:
    app: anylog-publisher
data:
  NODE_TYPE: "publisher"
  NODE_NAME: "publisher-node"
  COMPANY_NAME: "Company Name"
  #EXTERNAL_IP: <EXTERNAL IP>
  #LOCAL_IP: <LOCAL IP>
  ANYLOG_SERVER_PORT: "32248"
  ANYLOG_REST_PORT: "32249"
  MASTER_NODE: "100.115.6.90:32048"
  SYNC_TIME: "30 second"

  # An optional parameter for the number of workers threads that process requests which are send to the provided IP and Port.
  TCP_THREAD_POOL: "6"
  # Amount of time (in seconds) until REST timesout
  REST_TIMEOUT: "30"
  # The number of concurrent threads supporting HTTP requests.
  REST_THREADS: "5"
  # Sets the number of threads supporting queries (the default is 3).
  QUERY_POOL: "3"

# User should update DB_USER credentials
  DB_TYPE: "psql"
  DB_IP: "postgres"
  DB_USER: "admin"
  DB_PASSWD: "demo"

  # publisher specific configs
  # run publisher where compress_json=!compress_json and move_json=!move_json and master_node=!master_node and dbms_name=!dbms_file_location and table_name=!table_file_location
  COMPRESS_JSON: "true"
  MOVE_JSON: "true"
  # sample file name: [db_name].[table_name].0.0.json
  DBMS_FILE_LOCATION: "file_name[0]"
  TABLE_FILE_LOCATION: "file_name[1]"

  MQTT_ENABLE: "true"
  BROKER: "driver.cloudmqtt.com"
  MQTT_PORT: "18785"
  MQTT_USER: "ibglowct"
  MQTT_PASSWORD: "MSY4e009J7ts"
  MQTT_LOG: "false"
  MQTT_TOPIC_NAME: "anylogedgex"
  MQTT_TOPIC_DBMS: "db_name"
  # original value was "bring [device]" (Random-Integer-Generator01). howerver, due to a PSQL table name limit size is 65 chars, it's manually changeds to: rand_int
  MQTT_TOPIC_TABLE: "rand_data"
  MQTT_COLUMN_TIMESTAMP: "now"
  MQTT_COLUMN_VALUE_TYPE: "float"
  MQTT_COLUMN_VALUE: "bring [readings][][value]"

  DEPLOY_LOCAL_SCRIPT: "false"
