kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: {{ .Values.general.namespace }}
  name: {{ .Values.volume.name }}-claim
spec:
  storageClassName: {{ .Values.volume.specs.storage_class }}
  accessModes:
    - {{ .Values.volume.specs.access_mode }}
  resources:
    requests:
      storage: {{ .Values.volume.specs.storage_size }}
---
kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: {{ .Values.general.namespace }}
  name: {{ .Values.volume.name }}
spec:
  storageClassName: {{ .Values.volume.specs.storage_class }}
  capacity:
    storage: {{ .Values.volume.specs.storage_size }}
  accessModes:
    - {{ .Values.volume.specs.access_mode }}
  persistentVolumeReclaimPolicy: {{ .Values.volume.specs.retain_policy }}
  hostPath:
    path: {{ .Values.volume.specs.host_path }}
