# Remote-CLI
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: '{{ .Values.general.namespace }}'
  name: remote-cli
  labels:
    app: '{{ .Values.general.app_name }}'
spec:
  replicas: {{ .Values.general.replicas }}
  selector:
    matchLabels:
      app: '{{ .Values.general.app_name }}'
  template:
    metadata:
      labels:
        app: {{ .Values.general.app_name }}
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
      - name: remote-cli
        image: anylogco/remote-cli:latest
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: remote-cli-configs
        ports:
        - name: remote-cli-port
          containerPort: 31800
---
# AnyLog Query Node
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: '{{ .Values.metadata.namespace }}'
  name: '{{ .Values.metadata.deployment_name }}'
  labels:
    app: '{{ .Values.metadata.deployment_name }}'
spec:
  replicas: {{ .Values.metadata.replicas }}
  selector:
    matchLabels:
      app: '{{ .Values.metadata.deployment_name }}'
  template:
    metadata:
      labels:
        app: '{{ .Values.metadata.deployment_name }}'
    spec:
      hostname: {{ .Values.metadata.pod_name }}
      {{- if ne .Values.metadata.node_selector "" }}
      nodeSelector:
        kubernetes.io/hostname: {{ .Values.metadata.node_selector }}
      {{ end }}
      {{- if ne .Values.image.secret_name "" }}
      imagePullSecrets:
        - name: {{ .Values.image.secret_name }}
      {{ end }}
      containers:
      - name: '{{ .Values.metadata.deployment_name }}'
        image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
        imagePullPolicy: {{ .Values.image.pull_policy }}
        envFrom:
        - configMapRef:
            name: '{{ .Values.metadata.configmap_name }}'
        tty: true
        stdin: true
        ports:
        - name: server
          containerPort: {{ .Values.networking.ANYLOG_SERVER_PORT }}
        - name: rest
          containerPort: {{ .Values.networking.ANYLOG_REST_PORT }}
        {{ if ne .Values.networking.ANYLOG_BROKER_PORT "" }}
        - name: broker
          containerPort: {{ .Values.networking.ANYLOG_BROKER_PORT }}
        {{ end }}
