apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: '{{ .Values.general.namespace }}'
  name: remote-cli
  labels:
    app: '{{ .Values.general.app_name }}'
spec:
  replicas: {{ .Values.general.replicas }}
  selector:
    matchLabels:
      app: '{{ .Values.general.app_name }}'
  template:
    metadata:
      labels:
        app: {{ .Values.general.app_name }}
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
      - name: remote-cli
        image: anylogco/remote-cli:latest
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: remote-cli-configmaps
        ports:
        - name: remote-cli-port
          containerPort: 31800

        {{- if eq .Values.volume.enable_volume true }}
        volumeMounts:
          - name: remote-cli-json
            mountPath: /app/Remote-CLI/anylog_query/static/json
          - name: remote-cli-blobs
            mountPath: /app/Remote-CLI/anylog_query/static/blobs/current/
        {{ end }}
      {{- if eq .Values.volume.enable_volume true }}
      volumes:
        - name: remote-cli-json
          persistentVolumeClaim:
            claimName: remote-cli-json-pvc
        - name: remote-cli-blobs
          persistentVolumeClaim:
            claimName: remote-cli-blobs-pvc
      {{ end }}