general:
  namespace: default
  volume_name: postgres-pv
  # nodeSelector - Allows running Kubernetes remotely. If commented out, code will ignore it
  #nodeSelector: ""

spec:
  storage_class: manual
  access_mode: ReadWriteMany
  storage_size: 5Gi
  reclaim_policy: Retain
  host_path: /opt/postgres-data