general:
  namespace: default
  app_name: postgres
  deployment_name: postgres-app
  service_name: postgres-svs
  configmap_name: postgres-configs
  volume_name: postgres-pv
  enable_volume: true
  # nodeSelector - Allows running Kubernetes remotely. If commented out, code will ignore it
  #nodeSelector: ""
  replicas: 1
  
image:
  repository: postgres
  tag: 14.0-alpine
  pullPolicy: IfNotPresent

networking:
  port_name: psql-port
  port: 5432
  
credentials:
  username: admin
  password: demo
