apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.general.namespace }}
  name: {{ .Values.general.blob_volume }}-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.spec.storage_size }}
