version: '3'
services:
  db:
    image: mongo:latest
    restart: always
    container_name: mongodb
    stdin_open: true
    tty: true
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
    ports:
      - "${PORT}:${PORT}"
    expose:
      - "${PORT}"
    volumes:
      - db-data:/data/db
      - mongo-config:/data/configdb
volumes:
  db-data:
  mongo-config: