apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: '{{ .Values.metadata.namespace }}'
  name: '{{ .Values.metadata.pod_name }}-anylog-pvc'
  labels:
    app: '{{ .Values.metadata.app_name }}'
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
