apiVersion: v1
kind: ConfigMap
metadata:
  name: tools-configuration
  labels:
    app: anylog-tools
data:
  CONN_IP: 0.0.0.0
  GUI_PORT: 5000
  CLI_PORT: 8000
  CONFIG_FOLDER: views
  CONFIG_FILE: testnet.json
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: anylog-gui
  name: anylog-gui
spec:
  ports:
    - name: anylog-gui
      port: 5000
    - name: remote-cli
      port: 8000
  selector:
    io.kompose.service: anylog-tools
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: anylog-gui-statefulset
  labels:
    app: anylog-tools
spec:
  serviceName: anylog-tools
  replicas: 1
  selector:
    matchLabels:
      app: anylog-tools
  template:
    metadata:
      labels:
        app: anylog-tools
    spec:
      containers:
      - name: anylog-gui
        image: anylogco/anylog-gui:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: tools-configuration
        ports:
        - containerPort: 5000
          name: anylog-gui
        volumeMounts:
        - name: gui-pv-data
          mountPath: /app/AnyLog-GUI/anylog_query/static/json
      - name: remote-cli
        image: anylogco/remote-cli:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: tools-configuration
        ports:
        - containerPort: 8000
          name: remote-cli
        volumeMounts:
        - name: cli-pv-data
          mountPath: /app/Remote-CLI/anylog_query/static/json
      volumes:
      - name: cli-pv-data
        persistentVolumeClaim:
          claimName: cli-pv-claim


