apiVersion: v1
kind: ConfigMap
metadata:
  name: gui-configuration
  labels:
    app: anylog-gui
data:
  CONN_IP: "0.0.0.0"
  GUI_PORT: "5000"
  CONFIG_FOLDER: "views"
  CONFIG_FILE: "testnet.json"
---
apiVersion: v1
kind: Service
metadata:
  name: anylog-gui
  labels:
    app: anylog-gui
spec:
  ports:
  - port: 5000
    name: anylog-gui
  selector:
    app: anylog-gui
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: anylog-gui
  labels:
    app: anylog-gui
spec:
  serviceName: "anylog-gui"
  replicas: 1
  selector:
    matchLabels:
      app: anylog-gui
  template:
    metadata:
      labels:
        app: anylog-gui
    spec:
      containers:
      - name: anylog-gui
        image: anylogco/anylog-gui:latest
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: cli-configuration
        ports:
          - containerPort: 5000
            name: anylog-gui
#        volumeMounts:
#        - name: gui-pv-data
#          mountPath: /app/AnyLog-GUI/anylog_query/static/json
#      volumes:
#      - name: gui-pv-data
#        persistentVolumeClaim:
#          claimName: gui-pv-claim
#

