apiVersion: v1
kind: ConfigMap
metadata:
  name: node-configuration
  labels:
    app: anylog-node
data:
  NODE_TYPE: "rest"
  NODE_NAME: "anylog-node"
  COMPANY_NAME: "AnyLog"
  #EXTERNAL_IP: <EXTERNAL IP>
  #LOCAL_IP: <LOCAL IP>
  ANYLOG_SERVER_PORT: "32048"
  ANYLOG_REST_PORT: "32049"
  ANYLOG_BROKER_PORT: "32050"
  MASTER_NODE: "127.0.0.1:32048"
  SYNC_TIME: "30 second"

  # User should update DB_USER credentials
  DB_TYPE: "psql"
  DB_IP: "127.0.0.1"
  DB_USER: "admin"
  DB_PASSWD: "passwd"
  DB_IP: "postgres"
  DB_PORT: "5432"
  DEFAULT_DBMS: "test"

  CLUTSER_NAME: "new-cluster"
  ENABLE_PARTITION: "true"
  PARTITION_COLUMN: "timestamp"
  PARTITION_INTERVAL: "7 days"
  PARTITION_KEEP: "42"
  ENABLE_DATA_MONITOR: "false"
  TABLE_NAME: "*"
  INTERVAL_VALUE: "10"
  DATA_MONITOR_INTERVAL: "1 minute"
  DATA_MONITOR_COLUMN: "value"

  MQTT_ENABLE: "true"
  BROKER: "driver.cloudmqtt.com"
  MQTT_PORT: "18785"
  MQTT_USER: "ibglowct"
  MQTT_PASSWORD: "MSY4e009J7ts"
  MQTT_LOG: "false"
  MQTT_TOPIC_NAME: "anylogedgex"
  MQTT_TOPIC_DBMS: "test"
  MQTT_TOPIC_TABLE: "bring [device]"
  MQTT_COLUMN_TIMESTAMP: "now"
  MQTT_COLUMN_VALUE_TYPE: "float"
  MQTT_COLUMN_VALUE: "bring [readings][][value]"

---
apiVersion: v1
kind: Service
metadata:
  name: anylog-node
  labels:
    app: anylog-node
spec:
  ports:
  - port: 32048
    name: anylog-node-tcp
  - port: 32049
    name: anylog-node-rest
  - port: 32050
    name: anylog-node-broker
  selector:
    app: anylog-node
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: anylog-node
  labels:
    app: anylog-node
spec:
  imagePullSecrets:
    - name: myregistrykey
  serviceName: "anylog-node"
  replicas: 1
  selector:
    matchLabels:
      app: anylog-node
  template:
    metadata:
      labels:
        app: anylog-node
    spec:
      containers:
      - name: anylog-node
        image: anylogco/anylog-node:test
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: node-configuration
        ports:
          - containerPort: 32048
            name: tcp
          - containerPort: 32049
            name: rest
          - containerPort: 32050
            name: broker
#        volumeMounts:
#        - name: gui-pv-data
#          mountPath: /app/AnyLog-GUI/anylog_query/static/json
#      volumes:
#      - name: gui-pv-data
#        persistentVolumeClaim:
#          claimName: gui-pv-claim
#
