# Based On: https://medium.com/@suyashmohan/setting-up-postgresql-database-on-kubernetes-24a2a192e962
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-configuration
  labels:
    app: grafana
data:
  GRAFANA_ADMIN_USER: admin
  GRAFANA_ADMIN_PASSWORD: admin
  GF_AUTH_ANONYMOUS_ENABLED: "true"
  GF_AUTH_DISABLE_LOGIN_FORM: "false"
  GF_INSTALL_PLUGINS: "simpod-json-datasource,grafana-worldmap-panel"
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  ports:
  - port: 3000
    name: grafana
  selector:
    app: grafana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    io.kompose.service: grafana
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: grafana
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/frontend: "true"
        io.kompose.service: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:7.5.7
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: grafana-configuration
        ports:
        - containerPort: 3000
          name: grafana
        volumeMounts:
        - name: grafana-pv-data
          mountPath: /var/lib/grafana
      volumes:
      - name: grafana-pv-data
        persistentVolumeClaim:
          claimName: grafana-pv-claim
