# Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: psql-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/postgres/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psql-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: postgres
  lables:
    app: postgres
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: postgres


