# Service
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f /home/anylog/docker-compose/docker-compose-update.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: postgres
status:
  loadBalancer: {}

---
# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f /home/anylog/docker-compose/docker-compose-update.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f /home/anylog/docker-compose/docker-compose-update.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/frontend: "true"
        io.kompose.service: postgres
    spec:
      volumes:
        - name: pgdata
          hostPath:
            path: /mnt/postgres/data
      containers:
        - env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: secret-configs
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-configs
                key: POSTGRES_PASSWORD
          image: postgres:14.0-alpine
          imagePullPolicy: IfNotPresent
          name: postgres
          ports:
            - containerPort: 5432
          resources: {}
          stdin: true
          tty: true
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data/pgdata
      restartPolicy: Always
status: {}
