# Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: psql-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/postgres/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psql-volume-claim
sepc:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  storage: 1Gi

---
