# https://medium.com/@suyashmohan/setting-up-postgresql-database-on-kubernetes-24a2a192e962
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: microk8s-hostpath
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: microk8s.io/hostpath
---
