apiVersion: v1
kind: Service
metadata:
  name: postgres-headless-svc
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
    protocol: TCP
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: postgres-headless-svc
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        name: postgres
        image: postgres:14.0-alpine
        imagePullPolicy: "IfNotPresent"
        env:
          - name: POSTGRESQL_VOLUME_DIR
            value: "/bitnami/postgresql"
          - name: POSTGRES_USER
            valueFrom:
              configMap:
                map: secret-configs
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-configs
                key: POSTGRES_PASSWORD
        ports:
          - name: postgresql
            containerPort: 5432
            protocol: TCP


