apiVersion: v1
kind: Secret
metadata:
  name: secret-configs
data:
  POSTGRES_PASSWORD: cGFzc3dkCg== # passwd
#  GRAFANA_PASSWORD: cGFzc3dkCg== # passwd
#  MQTT_PASSWORD: TVNZNGUwMDlKN3RzCg== # MSY4e009J7ts

