
---
# Grafana volume
kind: PersistentVolume
apiVersion: v1
metadata:
  name: grafana-pv-data
  labels:
    app: grafana
    type: local
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/grafana/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-pv-claim
  labels:
    app: grafana
spec:
  storageClassName: microk8s-hostpath
  capacity:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# Remote-CLI volume
kind: PersistentVolume
apiVersion: v1
metadata:
  name: cli-pv-data
  labels:
    app: remote-cli
    type: local
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/AnyLog/Remote-CLI"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cli-pv-claim
  labels:
    app: remote-cli
spec:
  storageClassName: microk8s-hostpath
  capacity:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# AnyLog-GUI volume
kind: PersistentVolume
apiVersion: v1
metadata:
  name: gui-pv-data
  labels:
    app: anylog-gui
    type: local
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/AnyLog/AnyLog-GUI"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gui-pv-claim
  labels:
    app: anylog-gui
spec:
  storageClassName: microk8s-hostpath
  capacity:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi