version: "2.2"
services:
  anylog-operator2:
    image: anylogco/anylog-network:${TAG}
    restart: always
    env_file:
      - anylog_configs.env
      - advance_configs.env
    container_name: ${CONTAINER_NAME}
    stdin_open: true
    tty: true
    network_mode: "${NETWORK}"
#    ports:
#      - ${ANYLOG_SERVER_PORT}:${ANYLOG_SERVER_PORT}
#      - ${ANYLOG_REST_PORT}:${ANYLOG_REST_PORT}
    environment:
      - INIT_TYPE=${INIT_TYPE}
    volumes:
      - anylog-operator2-anylog:/app/AnyLog-Network/anylog
      - anylog-operator2-blockchain:/app/AnyLog-Network/blockchain
      - anylog-operator2-data:/app/AnyLog-Network/data
      - anylog-operator2-local-scripts:/app/deployment-scripts

volumes:
  anylog-operator2-anylog:
  anylog-operator2-blockchain:
  anylog-operator2-data:
  anylog-operator2-local-scripts: