version: "2.2"
services:
  anylog-node:
    image: anylogco/anylog-network:${BUILD}
    restart: always
    env_file:
      - anylog_configs.env
      - advance_configs.env
    environment:
      - NODE_TYPE: ${INIT_TYPE}
    container_name: ${CONTAINER_NAME}
    stdin_open: true
    tty: true
    network_mode: "${NETWORK}"
    volumes:
      - anylog-node-anylog:/app/AnyLog-Network/anylog
      - anylog-node-blockchain:/app/AnyLog-Network/blockchain
      - anylog-node-data:/app/AnyLog-Network/data
      - anylog-node-local-scripts:/app/deployment-scripts
volumes:
  anylog-node-anylog:
  anylog-node-blockchain:
  anylog-node-data:
  anylog-node-local-scripts:
